### ISSUE TITLE
Error in running gta.find_sources

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#111]
I am getting the following error when using version number 0.12.1 & ScienceTools 11-05-00

finder1=gta.find_sources(prefix='find',model=model1,sqrt_ts_threshold=5.0,min_separation=0.5,max_iter=10,sources_per_iter=20,tsmap_fitter='tsmap')

.... lots of lines ...
File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+138.g006a-py2.7.egg/fermipy/model_utils.py", line 177, in make_parameter_dict
    value, scale = utils.scale_parameter(o['value']*o['scale'])
TypeError: can't multiply sequence by non-int of type 'float'

Please help.

**Comment by woodmd** [comment]
Can you point me to the location of your analysis directory at SLAC?

**Comment by vaidehiratna** [comment]
/u/gl/vaidehi/fermi_disk/Individuals/CTA102

**Comment by woodmd** [comment]
I'm not able to reproduce this error for some reason.  Can you trying running again with the latest master?

**Comment by vaidehiratna** [comment]
I upgraded the version but still facing the same problem. Here is the full log

>>> finder1=gta.find_sources(prefix='find',model=model1,sqrt_ts_threshold=5.0,min_separation=0.5,max_iter=10,sources_per_iter=20,tsmap_fitter='tsmap')
2017-01-16 02:36:53 INFO    GTAnalysis.find_sources(): Starting.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/sourcefind.py", line 108, in find_sources
    srcs, peaks = self._find_sources_iterate(prefix, i, **config)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/sourcefind.py", line 181, in _find_sources_iterate
    **kw)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/tsmap.py", line 724, in tsmap
    maps = self._make_tsmap_fast(prefix, **config)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/tsmap.py", line 815, in _make_tsmap_fast
    loglevel=logging.DEBUG)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/gtanalysis.py", line 1476, in add_source
    src = self.roi.create_source(name, src_dict, rescale=True)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/roi_model.py", line 1393, in create_source
    rescale=rescale)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/roi_model.py", line 362, in create_from_dict
    rescale=rescale)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/roi_model.py", line 897, in create_from_dict
    rescale, False)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/model_utils.py", line 160, in create_pars_from_dict
    o[k] = make_parameter_dict(o[k], **kw)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/model_utils.py", line 177, in make_parameter_dict
    value, scale = utils.scale_parameter(o['value']*o['scale'])
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by woodmd** [comment]
What's the value of the `model` argument that you're passing to find_sources?

**Comment by vaidehiratna** [comment]
Here are the details

        name1='3FGL'
        name2='J2232.5+1143'
        srcname=name1+name2
        gta = GTAnalysis('%s.yaml' % srcname,logging={'verbosity' : 3})
        gta.setup()
        gta.optimize()
        gta.free_source('galdiff')
        gta.free_source('isodiff')
        gta.free_sources(minmax_ts=[25,None],pars='norm')
        gta.free_sources(minmax_ts=[1000,None],distance=5.0)
        gta.free_source(srcname)
        gta.free_source('3FGLJ2254.0+1608')
        gta.fit()
        gta.write_roi('fit_model_1')
        os.system('cp output/fit_model_1.npy .')
        p = np.load('fit_model_1.npy').flat[0]
        src = p['sources']['%s %s' %(name1,name2)]
        Spectrum1=src['SpectrumType']
        if src['ts']>=25 and Spectrum1=='PowerLaw':
                Index1,Index_err1=src['params']['Index']
        elif src['ts']>=25 and Spectrum1=='LogParabola':
                Index1,Index_err1=src['params']['alpha']
        else:
                Index1=2.4
        model1 = {'Index' : '%s' %(np.fabs(Index1)), 'SpatialModel' : 'PointSource'}
        finder1=gta.find_sources(prefix='find',model=model1,sqrt_ts_threshold=5.0,min_separation=0.5,max_iter=10,sources_per_iter=20,tsmap_fitter='tsmap')

**Comment by woodmd** [comment]
The problem is that you are passing `Index` as a string instead of a float.  Can you try the following:
```
model1 = {'Index' : np.fabs(Index1), 'SpatialModel' : 'PointSource'}
```

**Comment by vaidehiratna** [comment]
Yes. It is working nice.
Thanks.
