### ISSUE TITLE
Potential problem with fermipy-flux-sensitivity - stacktrace.

### ISSUE THREAD

**Issue by zimmerst** [fermiPy/fermipy#116]
Hi,
i'm trying to create flux sensitivity tables following this recipe: http://fermipy.readthedocs.io/en/latest/advanced/sensitivity.html#sensitivity

last week i was using the latest tag and things worked fine - however, with the change of tags, things appear broken. Below is the output if I run the minimal variant of it with 11-05-00 (ST:11-05-00), run with docker (11-05-00) on macOSX. 
```bash
[root@eac2f05eb71e fermipy]# fermipy-flux-sensitivity --galdiff=data/gll_iem_v06.fits --ltcube=data/P8_SOURCE_V6_239557414_428903014_z90_r180_gti_ft1_gtltcube.fits --output=test.fits
Traceback (most recent call last):
  File "/opt/conda/bin/fermipy-flux-sensitivity", line 6, in <module>
    sys.exit(fermipy.scripts.flux_sensitivity.main())
  File "/opt/conda/lib/python2.7/site-packages/fermipy/scripts/flux_sensitivity.py", line 250, in main
    args.event_class, event_types)
  File "/opt/conda/lib/python2.7/site-packages/fermipy/scripts/flux_sensitivity.py", line 60, in __init__
    ebins)]
  File "/opt/conda/lib/python2.7/site-packages/fermipy/irfs.py", line 206, in create
    aeff = create_aeff(event_class, et, evals, ltc.costh_center)
  File "/opt/conda/lib/python2.7/site-packages/fermipy/irfs.py", line 571, in create_aeff
    m[i, j] = irf.aeff().value(x, y, 0.0)
  File "/home/ScienceTools/python/pyIrfLoader.py", line 563, in value
    def value(*args): return _pyIrfLoader.IAeff_value(*args)
NotImplementedError: Wrong number of arguments for overloaded function 'IAeff_value'.
  Possible C/C++ prototypes are:
    value(double,astro::SkyDir const &,astro::SkyDir const &,astro::SkyDir const &,double)
    value(double,astro::SkyDir const &,astro::SkyDir const &,astro::SkyDir const &)
    value(double,double,double,double)
    value(double,double,double)
    value(std::vector<double,std::allocator<double > > const &,std::vector<double,std::allocator<double > > const &,std::vector<double,std::allocator<double > > const &,double)
    value(std::vector<double,std::allocator<double > > const &,std::vector<double,std::allocator<double > > const &,std::vector<double,std::allocator<double > > const &)

[root@eac2f05eb71e fermipy]# gtbin -v
This is gtbin version ScienceTools-11-05-00
```

I also tested the same command with 11-05-01 and the latest tag. Honestly i'm quite confused. I know it worked "last week" but looking through the change log there's nothing that sticks out. 
Lastly, looking at the source code of fermipy/irfs.py, the problem can be avoided by explicitly type-casting x and y as floats. 

```python
def create_aeff(event_class, event_type, egy, cth):
    irf = create_irf(event_class, event_type)
    irf.aeff().setPhiDependence(False)
    theta = np.degrees(np.arccos(cth))

    # Exposure Matrix                                                                                                                                                                                                  
    # Dimensions are Etrue and incidence angle                                                                                                                                                                         
    m = np.zeros((len(egy), len(cth)))
    for i, x in enumerate(egy):
        for j, y in enumerate(theta):
            m[i, j] = irf.aeff().value(x.astype("float"), y.astype("float"), 0.0)
    return m
```

i don't think this should break anything else.

**Comment by woodmd** [comment]
This should now be fixed by #117 which is in the 0.13.3 patch release.
