### ISSUE TITLE
source map generation

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#118]
I am trying to simulate a source whose spectrum is defined as a FileFunction. I have made a xml file as follows

<?xml version="1.0" ?>
<source_library title="source_library">
  <source name="J0310.8+3814" type="PointSource">
   
    <spectrum file="spectrum_J0310.8+3814.txt" type="FileFunction">
    <parameter free="1" max="1e5" min="1e-5" name="Normalization" scale="1" value="1.0"/>
   </spectrum>
   <spatialModel type="SkyDirFunction">
    <parameter free="0" max="360." min="-360." name="RA" scale="1.0" value="47.708"/>
    <parameter free="0" max="90." min="-90." name="DEC" scale="1.0" value="38.248"/>
   </spatialModel>
  </source>
</source_library>

In the config file, I am calling it as follows
model:
  src_radius : 15
  src_roiwidth : 15
  galdiff : '/afs/slac.stanford.edu/g/glast/ground/GLAST_EXT/diffuseModels/v5r0/gll_iem_v06.fits'
  isodiff : '/afs/slac.stanford.edu/g/glast/ground/GLAST_EXT/diffuseModels/v5r0/iso_P8R2_SOURCE_V6_v06.txt'
  catalogs :
    - 'J0310.8+3814.xml'

First I am running the setup command which will be followed by gta_simulate_roi command.
>>> name1='J0310.8+3814'
>>> gta = GTAnalysis('%s.yaml' % name1,logging={'verbosity' : 3})
>>> gta.setup()

It generates all the files but get stuck at srcmaps step. I get the following error

2017-02-09 11:53:02 INFO    GTBinnedAnalysis.run_gtapp(): Running gtsrcmaps.
2017-02-09 11:53:02 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtsrcmaps scfile=SC.fits sctable="SC_DATA" expcube=/u/gl/vaidehi/fermi_disk/LTCube_zmax_90.fits cmap=/nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/ccube_00.fits srcmdl=/nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/srcmdl_00.xml bexpmap=/nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/bexpmap_00.fits wmap=none outfile=/nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/srcmap_00.fits irfs="P8R2_SOURCE_V6" evtype=3 convol=yes resample=yes rfactor=2 minbinsz=0.05 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=4 clobber=yes debug=no gui=no mode="ql"
2017-02-09 11:53:16 INFO    GTBinnedAnalysis.run_gtapp(): This is gtsrcmaps version ScienceTools-11-05-01
2017-02-09 11:53:16 INFO    GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
2017-02-09 11:53:16 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6
2017-02-09 11:53:16 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  0  1
2017-02-09 11:53:16 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named J0310.8+3814
2017-02-09 11:53:16 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 13.46 s
2017-02-09 11:53:16 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
2017-02-09 11:53:16 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
2017-02-09 11:53:16 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Creating BinnedObs
2017-02-09 11:53:16 DEBUG   GTBinnedAnalysis._create_binned_analysis(): {'irfs': 'P8R2_SOURCE_V6', 'expCube': '/u/gl/vaidehi/fermi_disk/LTCube_zmax_90.fits', 'srcMaps': '/nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/srcmap_00.fits', 'binnedExpMap': '/nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/bexpmap_00.fits'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/gtanalysis.py", line 1198, in setup
    self._create_likelihood()
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/gtanalysis.py", line 1223, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.12.1+143.g93e6-py2.7.egg/fermipy/gtanalysis.py", line 4865, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-05-01/python/BinnedAnalysis.py", line 61, in __init__
    pyLike.AppHelpers_checkExposureMap(srcMaps, binnedExpMap)
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-05-01/python/pyLikelihood.py", line 3550, in AppHelpers_checkExposureMap
    return _pyLikelihood.AppHelpers_checkExposureMap(*args)
RuntimeError: File not found: /nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/srcmap_00.fits

I also ran the gtsrcmaps command, as printed above, outside fermiPy and got the following error
This is gtsrcmaps version ScienceTools-11-05-01
Using evtype=3 (i.e., FRONT/BACK irfs)
ResponseFunctions::load: IRF used: P8R2_SOURCE_V6
  event_types:  0  1
Creating source named J0310.8+3814
Floating point exception

I am using all sky event file and lt cube file as input. The path of the working directory is as follows
/u/gl/vaidehi/fermi_disk/EBL/Simulation/FSRQ/J0310.8+3814

Please help.

Thanks.

**Comment by woodmd** [comment]
It looks like gtsrcmaps is crashing because of the value of the chatter parameter:
```
/u/gl/vaidehi/fermi_disk/EBL/Simulation/FSRQ/J0310.8+3814/fermipy.log:2017-02-09 11:51:53 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtsrcmaps scfile=SC.fits sctable="SC_DATA" expcube=/u/gl/vaidehi/fermi_disk/LTCube_zmax_90.fits cmap=/nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/ccube_00.fits srcmdl=/nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/srcmdl_00.xml bexpmap=/nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/bexpmap_00.fits wmap=none outfile=/nfs/farm/g/glast/u/vaidehi/EBL/Simulation/FSRQ/J0310.8+3814/srcmap_00.fits irfs="P8R2_SOURCE_V6" evtype=3 convol=yes resample=yes rfactor=2 minbinsz=0.05 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=5 clobber=yes debug=no gui=no mode="ql"
/u/gl/vaidehi/fermi_disk/EBL/Simulation/FSRQ/J0310.8+3814/fermipy.log:2017-02-09 11:51:54 INFO    GTBinnedAnalysis.run_gtapp(): Parameter chatter: value 5 is greater than maximum value 4.
/u/gl/vaidehi/fermi_disk/EBL/Simulation/FSRQ/J0310.8+3814/fermipy.log:2017-02-09 11:51:54 INFO    GTBinnedAnalysis.run_gtapp(): Caught N5hoops12ApeExceptionE at the top level: Exception while querying for int parameter chatter for component gtsrcmaps; Ape exception code 35 (at hoops/build/redhat6-x86_64-64bit-gcc44-Optimized/src/hoops_ape.cxx: 575)
```
Did you intend to set chatter to 5?

**Comment by woodmd** [comment]
I also notice that one of the flux values in your spectrum file is negative.  I would try running again with all positive values.

**Comment by vaidehiratna** [comment]
While testing to understand the cause of the error, I set chatter=5 but brought it back to 4 when faced the error you quoted. It still crashed. On the other hand, I agree that I didn't notice the negative flux value in the spectrum.

**Comment by vaidehiratna** [comment]
I think fermiPy calculates flux_100/flux_1000 up to 10^5.5 MeV, which is almost 317 GeV. Earlier my model spectrum was defined up to 300 GeV, but to account for the extended E_max, I calculated it up to 320 GeV and that made the flux values negative. I am checking if I can keep it positive till 318 GeV.

**Comment by vaidehiratna** [comment]
No, the flux becomes negative even at 310 GeV.

**Comment by vaidehiratna** [comment]
We have corrected our script to generate positive fluxes in the spectrum file. Thanks for pointing out the error.
