### ISSUE TITLE
Issue in relocalization

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#128]
Hi,

I am trying to relocalize ROI sources but facing error.
Input:
>>> for s in gta.roi.sources:
...     if s.name!='isodiff':
...             if s.name!='galdiff':
...                     loc = gta.localize(s.name, update=True, dtheta_max=0.5)

It ran successfully for a couple of sources but failed for a few other objects
2017-04-08 16:28:36 INFO    GTAnalysis.localize(): Running localization for 3FGL J2232.5+1143
2017-04-08 16:28:41 INFO    GTAnalysis.free_source(): Freeing parameters for 3FGL J2232.5+1143     : ['norm']
2017-04-08 16:28:49 INFO    GTAnalysis._localize(): Localization completed with new position:
(  ra, dec) = (  338.1625 +/-   0.0025,   11.7231 +/-   0.0024)
(glon,glat) = (   77.4418 +/-   0.0025,  -38.5952 +/-   0.0025)
offset =   0.0228 r68 =   0.0037 r95 =   0.0060 r99 =   0.0075
2017-04-08 16:28:49 INFO    GTAnalysis._localize(): Localization succeeded.
2017-04-08 16:28:49 INFO    GTAnalysis._localize(): Updating source 3FGL J2232.5+1143 to localized position.
2017-04-08 16:28:49 INFO    GTAnalysis.delete_source(): Deleting source 3FGL J2232.5+1143
2017-04-08 16:28:49 INFO    GTAnalysis.add_source(): Adding source 3FGL J2232.5+1143
Generating SourceMap for 3FGL J2232.5+1143....................!
2017-04-08 16:28:53 INFO    GTAnalysis._localize(): LogLike:   -29837.873 DeltaLogLike:       43.337
2017-04-08 16:28:53 INFO    GTAnalysis.localize(): Finished localization.
.....
.....
2017-04-08 16:29:43 INFO    GTAnalysis.localize(): Running localization for 3FGL J2254.0+1608
2017-04-08 16:29:47 INFO    GTAnalysis.free_source(): Freeing parameters for 3FGL J2254.0+1608     : ['Prefactor']
2017-04-08 16:29:57 INFO    GTAnalysis._localize(): Localization completed with new position:
(  ra, dec) = (  343.3698 +/-      nan,   16.1639 +/-      nan)
(glon,glat) = (   85.9995 +/-      nan,  -38.1063 +/-      nan)
offset =   0.1280 r68 =      nan r95 =      nan r99 =      nan
2017-04-08 16:29:57 WARNING GTAnalysis._localize(): Fit to localization contour failed.
2017-04-08 16:29:57 WARNING GTAnalysis._localize(): Localization failed.  Keeping existing position.
2017-04-08 16:29:57 INFO    GTAnalysis.localize(): Finished localization.
2017-04-08 16:29:57 INFO    GTAnalysis.localize(): Running localization for 3FGL J2219.2+1806
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.14.1+3.g7a9e-py2.7.egg/fermipy/sourcefind.py", line 274, in localize
    loc = self._localize(name, **config)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.14.1+3.g7a9e-py2.7.egg/fermipy/sourcefind.py", line 345, in _localize
    use_pylike=False)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.14.1+3.g7a9e-py2.7.egg/fermipy/sourcefind.py", line 517, in _fit_position_tsmap
    peaks = find_peaks(tsmap['ts'], 4.0, 0.2)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.14.1+3.g7a9e-py2.7.egg/fermipy/sourcefind_utils.py", line 178, in find_peaks
    slices = scipy.ndimage.find_objects(labeled)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/scipy/ndimage/measurements.py", line 270, in find_objects
    max_label = input.max()
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

Please help in this regard.

**Comment by woodmd** [comment]
The fact that you were able to trigger an exception is a bug but in general the relocalization method doesn't really work for sources outside the ROI.  In your loop I would add a cut on `offset_roi_edge` to restrict yourself to sources inside the ROI, e.g.
```
if s['offset_roi_edge'] > -0.1: continue
```
This will require sources to be at least 0.1 deg from the edge of the ROI.

Also I don't recommend running with untagged releases unless absolutely necessary (there is a bug fix or feature in master that is essential for your analysis).  We generally try to keep master stable but sometimes subtle bugs can creep in.  You can install the latest tagged release with pip like so:
```
# Make a new install of latest tag
pip install fermipy --user
# Upgrade to the latest tag
pip install fermipy --upgrade --no-deps --user 
```
To check your current verison do:
```
pip show fermipy
```
If everything has worked correctly the version tag should only contain major/minor/patch version numbers (e.g. 0.14.1).
