### ISSUE TITLE
File not found srcmap_00.fits

### ISSUE THREAD

**Issue by imereu** [fermiPy/fermipy#170]
I have this problem with srcmap. 

Plotter is MatPlotlib
2017-12-20 07:46:40 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 0.15.1+61.g5e03 
ScienceTools version 
PGW_6_J1706+4316
PGW_5_J1710+4327
isodiff
galdiff
gal_diffuse
iso_diffuse
2017-12-20 07:46:41 INFO    GTAnalysis.setup(): Running setup.
2017-12-20 07:46:41 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2017-12-20 07:46:41 INFO    GTBinnedAnalysis._select_data(): Skipping data selection.
2017-12-20 07:46:41 INFO    GTBinnedAnalysis.setup(): Using external LT cube.
2017-12-20 07:46:43 INFO    GTBinnedAnalysis._create_expcube(): Skipping gtexpcube.
WARNING: FITSFixedWarning: RADECSYS= 'FK5 ' 
the RADECSYS keyword is deprecated, use RADESYSa. [astropy.wcs.wcs]
2017-12-20 07:46:47 INFO    GTBinnedAnalysis.run_gtapp(): Running gtsrcmaps.
2017-12-20 07:46:47 INFO    GTBinnedAnalysis.run_gtapp(): time -p /home/fermiuser/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.17-without-root/x86_64-unknown-linux-gnu-libc2.17/bin/gtsrcmaps scfile=/home/fermiuser/Documenti/transient/ft2_2010.fits sctable="SC_DATA" expcube=/home/fermiuser/Documenti/transient/ltcube_028_zmax105.fits cmap=/home/fermiuser/Documenti/transient/PGW_6_J1706+4316/data/ccube_00.fits srcmdl=/home/fermiuser/Documenti/transient/PGW_6_J1706+4316/data/srcmdl_00.xml bexpmap=/home/fermiuser/Documenti/transient/PGW_6_J1706+4316/data/bexpmap_00.fits outfile=/home/fermiuser/Documenti/transient/PGW_6_J1706+4316/data/srcmap_00.fits irfs="P8R2_SOURCE_V6" evtype=3 convol=yes resample=yes rfactor=2 minbinsz=0.05 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=3 clobber=yes debug=no gui=no mode="ql"
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): This is gtsrcmaps version ScienceTools-v10r0p5-fssc-20150518
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  0  1
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named PGW_6_J1706+4316
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named PGW_5_J1710+4327
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named isodiff
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named galdiff
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named gal_diffuse
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): Function::parameter(std::string &):
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): A Parameter named  is not a Parameter of Function
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): 
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): Caught N10optimizers17ParameterNotFoundE at the top level: Function::parameter(std::string &):
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): A Parameter named  is not a Parameter of Function
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): 
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 12.81 s
2017-12-20 07:47:00 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
2017-12-20 07:47:00 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
Traceback (most recent call last):
  File "../scripts/runLCDayly.py", line 51, in <module>
    main()
  File "../scripts/runLCDayly.py", line 33, in main
    gta.setup()
  File "/home/fermiuser/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1023, in setup
    self._create_likelihood()
  File "/home/fermiuser/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1048, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/home/fermiuser/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 4983, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/home/fermiuser/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.17-without-root/x86_64-unknown-linux-gnu-libc2.17/lib/python/BinnedAnalysis.py", line 44, in __init__
    pyLike.AppHelpers_checkExposureMap(srcMaps, binnedExpMap)
  File "/home/fermiuser/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.17-without-root/x86_64-unknown-linux-gnu-libc2.17/lib/python/pyLikelihood.py", line 4567, in AppHelpers_checkExposureMap
    return lib_pyLikelihood.AppHelpers_checkExposureMap(*args)
RuntimeError: File not found: /home/fermiuser/Documenti/transient/PGW_6_J1706+4316/data/srcmap_00.fits

**Comment by woodmd** [comment]
Just to clarify... is this the same issue you emailed me about and were you able to resolve this issue?

**Comment by dimauromattia** [comment]
Hi @imereu ,

Could you provide more informations on your analysis? If you share a tarball of your analysis directory I can try to debug this further.

Best

Mattia

**Comment by Time-Cheung** [comment]
I also have this problem. Have you solved it?

**Comment by Alex-Broughton** [comment]
I too have this issue. Can you please post your solution?

**Comment by me-manu** [comment]
The underlying problem might be an issue with the srcmap computation in the fermitools. This is reported and hopefully resolved at some point: https://github.com/fermi-lat/Fermitools-conda/issues/59

**Comment by sarabuson** [comment]
Hi @me-manu, unfortunately the issue that you mentioned has not been solved. Tom is looking into it. If you have found a solution meanwhile, please share it : )

**Comment by Time-Cheung** [comment]
Hi, maybe you can try to use “gll_psc_v23.xml” as your input model instead of “gll_psc_v23.fits”.

 

发件人: noreply@github.com <noreply@github.com> 代表 Alex Broughton
发送时间: 2020年11月3日 7:00
收件人: fermiPy/fermipy <fermipy@noreply.github.com>
抄送: Time-Cheung <lhoovpee@163.com>; Comment <comment@noreply.github.com>
主题: Re: [fermiPy/fermipy] File not found srcmap_00.fits (#170)

 

I too have this issue. Can you please post your solution?
