### ISSUE TITLE
make_plot=True

### ISSUE THREAD

**Issue by imereu** [fermiPy/fermipy#177]
If have the option 
make_plot=True
after this, everything I try to do I have this error:
RuntimeError: Cannot read keyword "CRPIX1" in file "/home/LabAstrofisica/analysis/PGW_1_J0016+0006/data/srcmap_00.fits" (CFITSIO ERROR 409: bad string to double convert)

**Comment by imereu** [comment]
I have tried it again and the problem exactly born when I try to do make_plot=True a second time.

**Comment by woodmd** [comment]
I think you're going to have to provide a little more detail.  Can you share a tarball of your analysis directory?

**Comment by TarekHC** [comment]
Hi @imereu , 

Perhaps this is stupid... But wherever you are using "make_plot=True" could you try doing "make_plots=True"? (note the additional "s")

**Comment by imereu** [comment]
@TarekHC 
I have used make_plots not make_plot

**Comment by imereu** [comment]
@woodmd 
I work on my pc.
For more details I have in my analysis program these commands (for example):
**loc = gta.localize(src_name, free_radius=1.0, update=True, make_plots=True)
print(loc['ra'],loc['dec'],loc['pos_r68'],loc['pos_r95'])
gta.print_roi()
print(gta.roi[src_name])
gta.write_roi('fit1',make_plots=True)**

And the output is:


_2018-02-12 12:40:08 INFO    GTAnalysis.localize(): Running localization for PGW_1_J0016+0006
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
2018-02-12 12:40:59 INFO    GTAnalysis._localize(): Localization succeeded.
2018-02-12 12:40:59 INFO    GTAnalysis._localize(): Updating source PGW_1_J0016+0006 to localized position.
2018-02-12 12:40:59 INFO    GTAnalysis.delete_source(): Deleting source PGW_1_J0016+0006
2018-02-12 12:40:59 INFO    GTAnalysis.add_source(): Adding source PGW_1_J0016+0006
Generating SourceMap for PGW_1_J0016+0006....................!
2018-02-12 12:41:02 INFO    GTAnalysis._localize(): Localization completed with new position:
(  ra, dec) = (    4.0290 +/-   0.0993,   -0.2213 +/-   0.1022)
(glon,glat) = (  103.9836 +/-   0.1046,  -61.7867 +/-   0.0968)
offset =   0.0708 r68 =   0.1515 r95 =   0.2444 r99 =   0.3031
2018-02-12 12:41:02 INFO    GTAnalysis._localize(): LogLike:   -20415.951 DeltaLogLike:        0.374
2018-02-12 12:41:02 INFO    GTAnalysis.localize(): Finished localization.
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
2018-02-12 12:41:06 INFO    GTAnalysis.localize(): Execution time: 58.92 s
(4.028974532611766, -0.22130271049277617, 0.15145266632570736, 0.24441419026052147)
2018-02-12 12:41:06 INFO    GTAnalysis.print_roi(): 
name                SpatialModel   SpectrumType     offset        ts       npred
--------------------------------------------------------------------------------
PGW_1_J0016+0006    PointSource    PowerLaw          0.071     57.53       163.7
PGW_2_J0030+0446    PointSource    PowerLaw          6.214    111.60       143.4
TS44-1399           PointSource    PowerLaw          7.247      7.54        10.9
PGW_3_J2340-0538    PointSource    PowerLaw         10.515     -0.00         0.0
PGW_1_J2340-0550    PointSource    PowerLaw         10.526     -0.00         0.0
PGW_7_J0049-0934    PointSource    PowerLaw         12.623     -0.00         0.0
isodiff             ConstantValue  FileFunction      -----    147.92      1616.2
galdiff             MapCubeFunctio PowerLaw          -----    384.75      2059.0

Name           : PGW_1_J0016+0006
Associations   : ['PGW_1_J0016+0006']
RA/DEC         :      4.029/    -0.221
GLON/GLAT      :    103.984/   -61.787
TS             : 57.53
Npred          : 163.74
Flux           : 1.437e-07 +/-  2.6e-08
EnergyFlux     : 3.155e-05 +/- 5.21e-06
SpatialModel   : PointSource
SpectrumType   : PowerLaw
Spectral Parameters
Prefactor      :  3.869e-12 +/-  1.085e-12
Index          :     -2.832 +/-     0.1764
Scale          :       1000 +/-        nan
2018-02-12 12:41:06 INFO    GTBinnedAnalysis.write_xml(): Writing /home/LabAstrofisica/analysis/PGW_1_J0016+0006prova3/data/fit1_00.xml...
2018-02-12 12:41:06 INFO    GTAnalysis.write_fits(): Writing /home/LabAstrofisica/analysis/PGW_1_J0016+0006prova3/data/fit1.fits...
2018-02-12 12:41:07 INFO    GTAnalysis.write_roi(): Writing /home/LabAstrofisica/analysis/PGW_1_J0016+0006prova3/data/fit1.npy...
Traceback (most recent call last):
  File "runLC.py", line 95, in <module>
    main()
  File "runLC.py", line 73, in main
    gta.write_roi('fit1',make_plots=True)
  File "/home/LabAstrofisica/miniconda2/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 3461, in write_roi
    **kwargs.get('plotting', {}))
  File "/home/LabAstrofisica/miniconda2/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 3531, in make_plots
    mcube_map = self.model_counts_map()
  File "/home/LabAstrofisica/miniconda2/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1200, in model_counts_map
    maps = [c.model_counts_map(name, exclude) for c in self.components]
  File "/home/LabAstrofisica/miniconda2/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 4622, in model_counts_map
    self.like.logLike.buildFixedModelWts()
  File "/home/LabAstrofisica/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.17-without-root/x86_64-unknown-linux-gnu-libc2.17/lib/python/pyLikelihood.py", line 6302, in buildFixedModelWts
    return lib_pyLikelihood.BinnedLikelihood_buildFixedModelWts(*args)
RuntimeError: Cannot read keyword "CRPIX1" in file "/home/LabAstrofisica/analysis/PGW_1_J0016+0006prova3/data/srcmap_00.fits" (CFITSIO ERROR 409: bad string to double convert)_

**Comment by imereu** [comment]
Now I'm using fermipy version 0.16.0+157.g8552

**Comment by imereu** [comment]
I have update Fermipy and now there are no errors.
