### ISSUE TITLE
WCS / projections not supported anymore for PSF-component analysis  - potential conflict with gammapy

### ISSUE THREAD

**Issue by zimmerst** [fermiPy/fermipy#203]
Following #200 resolution, to switch to the development version of fermipy, indeed, the original issue is fixed. However, seemingly the switch to gammapy has broken the WCS/projection facilities. The aim is to combine multiple PSF classes as described in the fermipy documentation. Below is a traceback illustrating the issue:

```
2018-03-12 06:25:35 INFO    GTBinnedAnalysis._create_srcmaps(): Skipping gtsrcmaps.
2018-03-12 06:25:35 INFO    GTBinnedAnalysis.setup(): Finished setup for component 03
2018-03-12 06:25:35 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
2018-03-12 06:26:05 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 01.
2018-03-12 06:26:36 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 02.
2018-03-12 06:27:06 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 03.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-f6d4f0d76349> in <module>()
      1 matplotlib.interactive(True)
      2 gta = GTAnalysis('configuration.yaml')
----> 3 gta.setup()
      4 
      5 def plot_model(name,gta):

/nfs/farm/g/glast/u/zimmer/FermiData/Coma10/fermipy/gtanalysis.pyc in setup(self, init_sources, overwrite, **kwargs)
   1035 
   1036         # Create likelihood
-> 1037         self._create_likelihood()
   1038 
   1039         # Determine tmin, tmax

/nfs/farm/g/glast/u/zimmer/FermiData/Coma10/fermipy/gtanalysis.pyc in _create_likelihood(self, srcmdl)
   1065         self.like.model = self.like.components[0].model
   1066         self._fitcache = None
-> 1067         self._init_roi_model()
   1068 
   1069     def _init_roi_model(self):

/nfs/farm/g/glast/u/zimmer/FermiData/Coma10/fermipy/gtanalysis.pyc in _init_roi_model(self)
   1100             shape = (self.enumbins, np.max(self.geom.npix))
   1101 
-> 1102         self._coadd_maps(cmaps, shape, rm, wmaps)
   1103 
   1104     def _init_source(self, name):

/nfs/farm/g/glast/u/zimmer/FermiData/Coma10/fermipy/gtanalysis.pyc in _coadd_maps(self, cmaps, shape, rm, wmaps)
   3915         self._ccube = skymap.coadd_maps(self.geom, cmaps)
   3916         self._wcube = skymap.coadd_maps(self.geom, wmaps)
-> 3917         self._ccube.write(self.files['ccube'], conv='fgst-ccube')
   3918 
   3919         if self.projtype == "WCS":

/u/gl/zimmer/.local/lib/python2.7/site-packages/gammapy/maps/base.pyc in write(self, filename, **kwargs)
    264             This option is only compatible with the 'gadf' format.
    265         """
--> 266         hdulist = self.to_hdulist(**kwargs)
    267         overwrite = kwargs.get('overwrite', True)
    268         hdulist.writeto(filename, overwrite=overwrite)

/u/gl/zimmer/.local/lib/python2.7/site-packages/gammapy/maps/wcsmap.pyc in to_hdulist(self, hdu, hdu_bands, sparse, conv)
    156             hdu_bands_out = self.geom.make_bands_hdu(hdu=hdu_bands,
    157                                                      hdu_skymap=hdu,
--> 158                                                      conv=conv)
    159             hdu_bands = hdu_bands_out.name
    160         else:

/u/gl/zimmer/.local/lib/python2.7/site-packages/gammapy/maps/geom.pyc in make_bands_hdu(self, hdu, hdu_skymap, conv)
    961         cols = make_axes_cols(self.axes, axis_names)
    962         cols += self._make_bands_cols()
--> 963         return fits.BinTableHDU.from_columns(cols, header, name=hdu)
    964 
    965     @abc.abstractmethod

/nfs/farm/g/glast/u/zimmer/envs/fermipy/lib/python2.7/site-packages/astropy/io/fits/hdu/table.pyc in from_columns(cls, columns, header, nrows, fill, **kwargs)
    124 
    125         coldefs = cls._columns_type(columns)
--> 126         data = FITS_rec.from_columns(coldefs, nrows=nrows, fill=fill)
    127         hdu = cls(data=data, header=header, **kwargs)
    128         coldefs._add_listener(hdu)

/nfs/farm/g/glast/u/zimmer/envs/fermipy/lib/python2.7/site-packages/astropy/io/fits/fitsrec.pyc in from_columns(cls, columns, nrows, fill)
    340                     nrows = dim
    341 
--> 342         raw_data = np.empty(columns.dtype.itemsize * nrows, dtype=np.uint8)
    343         raw_data.fill(ord(columns._padding_byte))
    344         data = np.recarray(nrows, dtype=columns.dtype, buf=raw_data).view(cls)

/nfs/farm/g/glast/u/zimmer/envs/fermipy/lib/python2.7/site-packages/astropy/utils/decorators.pyc in __get__(self, obj, owner)
    496             return obj.__dict__[self._key]
    497         except KeyError:
--> 498             val = self.fget(obj)
    499             obj.__dict__[self._key] = val
    500             return val

/nfs/farm/g/glast/u/zimmer/envs/fermipy/lib/python2.7/site-packages/astropy/io/fits/column.pyc in dtype(self)
   1433             fields.append((name, dt))
   1434 
-> 1435         return nh.realign_dtype(np.dtype(fields), offsets)
   1436 
   1437     @lazyproperty

TypeError: data type not understood
```

The relevant configuration is here
```
binning:
  roiwidth   : 8.0
  binsz      : 0.1
  binsperdec : 8
  projtype   : WCS
  proj       : AIT

selection :
  logemin: 2.
  logemax : 5.9030899869919438
  zmax    : 90
  evclass : 128
  evtype  : 3
  tmin    : 239557414
  tmax    : 428903014
  filter  : null
  ra   :  0.
  dec  :  0.

components:
  - model: {isodiff: $FERMI_DIFFUSE_DIR/iso_P8R2_SOURCE_V6_PSF0_v06.txt}
    selection: {evtype: 4, zmax: 80}
    data: {ltcube: ltcube_00.fits}
  - model: {isodiff: $FERMI_DIFFUSE_DIR/iso_P8R2_SOURCE_V6_PSF1_v06.txt}
    selection: {evtype: 8, zmax: 85}
    data: {ltcube: ltcube_01.fits}
  - model: {isodiff: $FERMI_DIFFUSE_DIR/iso_P8R2_SOURCE_V6_PSF2_v06.txt}
    selection: {evtype: 16, zmax: 95}
    data: {ltcube: ltcube_02.fits}
  - model: {isodiff: $FERMI_DIFFUSE_DIR/iso_P8R2_SOURCE_V6_PSF3_v06.txt}
    selection: {evtype: 32, zmax: 100}
    data: {ltcube: ltcube_03.fits}

```

**Comment by cdeil** [comment]
@zimmerst - Do you know what the issue is here?

Is it a bug in `gammapy.maps`, or an incompatibility of how it's called from Fermipy?
Are you able to extract a regression test case that could be added to the Gammapy or Fermipy automated tests?

Let me know if you need help to pin this issue down or fix it. It would take me a while to get set up with Fermi ST / Fermipy and reproduce the issue, but I could do it. (Gammapy maintainer here, not done Fermi-LAT analysis since several years.)

**Comment by woodmd** [comment]
I'm doubtful this is a bug in `gammapy.maps` but I'll need to have a closer look to be sure.  I'll try to have a look at it this weekend.  One thing to check is whether you can run the same analysis with a single component (for instance the same configuration with the last three elements of `components` removed).

**Comment by zimmerst** [comment]
Hi @woodmd, @cdeil  - 
since posting, I have gone back and already in the setup of a single component, the following error is raised:

```
2018-03-13 11:40:48 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis
2018-03-13 11:40:48 DEBUG   GTBinnedAnalysis._create_binned_analysis(): {'minbinsz': 0.05, 'convolve': True, 'optimizer': 'MINUIT', 'resamp_fact': 2, 'srcModel': '/nfs/farm/g/glast/u/zimmer/FermiData/Coma10/PSF00/srcmdl_00.xml', 'resample': True, 'wmap': None}
2018-03-13 11:41:04 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Enabling energy dispersion
2018-03-13 11:41:04 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Disabling energy dispersion for isodiff
2018-03-13 11:41:04 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Disabling energy dispersion for galdiff
2018-03-13 11:41:04 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Computing fixed weights
2018-03-13 11:41:06 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Updating source maps
Traceback (most recent call last):
  File "prep.py", line 16, in <module>
    gta.setup()
  File "/u/gl/zimmer/.local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1037, in setup
    self._create_likelihood()
  File "/u/gl/zimmer/.local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1067, in _create_likelihood
    self._init_roi_model()
  File "/u/gl/zimmer/.local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1102, in _init_roi_model
    self._coadd_maps(cmaps, shape, rm, wmaps)
  File "/u/gl/zimmer/.local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 3917, in _coadd_maps
    self._ccube.write(self.files['ccube'], conv='fgst-ccube')
  File "/u/gl/zimmer/.local/lib/python2.7/site-packages/gammapy/maps/base.py", line 266, in write
    hdulist = self.to_hdulist(**kwargs)
  File "/u/gl/zimmer/.local/lib/python2.7/site-packages/gammapy/maps/wcsmap.py", line 158, in to_hdulist
    conv=conv)
  File "/u/gl/zimmer/.local/lib/python2.7/site-packages/gammapy/maps/geom.py", line 963, in make_bands_hdu
    return fits.BinTableHDU.from_columns(cols, header, name=hdu)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/io/fits/hdu/table.py", line 126, in from_columns
    data = FITS_rec.from_columns(coldefs, nrows=nrows, fill=fill)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 342, in from_columns
    raw_data = np.empty(columns.dtype.itemsize * nrows, dtype=np.uint8)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/utils/decorators.py", line 498, in __get__
    val = self.fget(obj)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/io/fits/column.py", line 1435, in dtype
    return nh.realign_dtype(np.dtype(fields), offsets)
TypeError: data type not understood
```

I'm not quite sure how to reproduce the issue but i'll try to put together a self-contained example.

**Comment by cdeil** [comment]
@zimmerst - A self-contained example would be great.

If it's hard to produce, you could also try to enter the debugger e.g. via
```
ipython --pdb myscript.py
```
and then move to this frame:
```
File "/u/gl/zimmer/.local/lib/python2.7/site-packages/gammapy/maps/geom.py", line 963, in make_bands_hdu
    return fits.BinTableHDU.from_columns(cols, header, name=hdu)
```
and find out what the problem is, i.e. where the type doesn't look OK (e.g. by printing cols and header).

Another thought: is this with Astropy 1.2? Maybe that really isn't working with `gammapy.maps`, at least I don't think I ever tried that.

**Comment by woodmd** [comment]
I confirm that I see the same error running with astropy 1.2.1.  The error is thrown when unicode strings are passed as record labels to `np.dtype`.  Using a newer astropy release (e.g. 2.0.4) resolves this error (this is also why we didn't see it in our normal regression tests).  As I suggested in #204 I think the best approach is just to create your own anaconda installation with the latest version of astropy.

**Comment by dimauromattia** [comment]
Hi Stephan, Did you try to run the analysis using a newer version of astropy? Is the issue fixed?

**Comment by zimmerst** [comment]
Ciao @dimauromattia , indeed, with version: fermipy version 0.16.0+179.g1a8e , this issue is fixed.
