### ISSUE TITLE
merit-skimmer broken in fermipy-dev

### ISSUE THREAD

**Issue by zimmerst** [fermiPy/fermipy#204]
Similar to #203 the previous PR seems to have broken the package dependencies for merit-skimmer

```
Traceback (most recent call last):
  File "/u/gl/zimmer/.local/bin/fermipy-merit-skimmer", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 662, in _build_master
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 675, in _build_from_requirements
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 859, in resolve
pkg_resources.ContextualVersionConflict: (astropy 1.2.1 (/afs/slac.stanford.edu/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages), Requirement.parse('astropy>=1.3'), set(['gammapy']))
```

**Comment by cdeil** [comment]
@zimmerst - Which command did you execute?
Does this error occur during an install or after install just by executing `fermipy-merit-skimmer`.

It's not that easy for us to go back and add support for Astropy 1.2.1 and make a new release for Gammapy just for this. Probably there's a simple flag to tell pip to ignore the version conflict if this is during install. Please try to find a workaround or give a bit more infos and I'll try to help find a solution.

**Comment by woodmd** [comment]
Adding support for Astropy 1.2.1 is probably not worth the effort at this point.  The only reason we were trying to support it in fermipy up to now is that it was the version included with the common python installation at SLAC.  I asked Heather to create a new python installation a while back -- if you'd like to have a common python installation that works with the latest version of fermipy I'd suggest you ping her again about this.

Alternatively it's relatively straightforward to create your own python installation and use that in lieu of the common installation.  [Here](https://github.com/fermiPy/fermipy/wiki/Creating-an-Anaconda-Python-Installation-at-SLAC) are some instructions I put together while back.  Using your own installation has the advantage of giving you total control over package versions and also tends to work better with conda environments.  In fact going forward we should probably make this the standard installation procedure for those working at SLAC.

**Comment by cdeil** [comment]
Yes, if upgrade to Astropy 1.3 (or even the LTS 2.x) is possible (or installing that version in a local env that comes first in the import search path), then that's the best solution.

I still find it curious that you didn't get this version conflict error on install, but now from `pkg_resources` on init. I've looked around a bit, but for the cases of `VersionConflict` from `pkg_resources` I found, all advised to upgrade, no good workaround to ignore the error was mentioned (only hacking around version numbers in `site-packages` or `setup.py` and reinstalling). I  think probably `gammapy.maps` would work just fine with Astropy 1.2, we just put 1.3 as minimum because of other parts of Gammapy.

Hope you find a solution!?

**Comment by zimmerst** [comment]
I confirm that the latest version of fermipy (installed locally) fixed this issue. Closing it.
```
rhel6-64i:FL8Y_HPX $ fermipy-merit-skimmer
usage: Usage: fermipy-merit-skimmer  [files or file lists] [options]
fermipy-merit-skimmer: error: too few arguments
```
