### ISSUE TITLE
Error in opening the ccube.fits file during the creation of the setup (gta.setup())

### ISSUE THREAD

**Issue by principe91** [fermiPy/fermipy#209]
Using the last version (0.16.0+170.gf71ab ) it makes correctly all the basic steps from gtselect to gtsrcmaps, then at the moment of the creation of the setup it returns error when it tries to access at the cube file.

2018-03-20 07:36:43 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 201.45 s
2018-03-20 07:36:43 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
2018-03-20 07:36:43 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
Traceback (most recent call last):
  File "scripts/apps/fermipy_analysis_pipeline4.py", line 23, in <module>
    gta.setup()
  File "/u/gl/principe/.local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1037, in setup
    self._create_likelihood()
  File "/u/gl/principe/.local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1067, in _create_likelihood
    self._init_roi_model()
  File "/u/gl/principe/.local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1102, in _init_roi_model
    self._coadd_maps(cmaps, shape, rm, wmaps)
  File "/u/gl/principe/.local/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 3917, in _coadd_maps
    self._ccube.write(self.files['ccube'], conv='fgst-ccube')
  File "/u/gl/principe/.local/lib/python2.7/site-packages/gammapy/maps/base.py", line 266, in write
    hdulist = self.to_hdulist(**kwargs)
  File "/u/gl/principe/.local/lib/python2.7/site-packages/gammapy/maps/wcsmap.py", line 158, in to_hdulist
    conv=conv)
  File "/u/gl/principe/.local/lib/python2.7/site-packages/gammapy/maps/geom.py", line 963, in make_bands_hdu
    return fits.BinTableHDU.from_columns(cols, header, name=hdu)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/io/fits/hdu/table.py", line 126, in from_columns
    data = FITS_rec.from_columns(coldefs, nrows=nrows, fill=fill)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 342, in from_columns
    raw_data = np.empty(columns.dtype.itemsize * nrows, dtype=np.uint8)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/utils/decorators.py", line 498, in __get__
    val = self.fget(obj)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/io/fits/column.py", line 1435, in dtype
    return nh.realign_dtype(np.dtype(fields), offsets)
TypeError: data type not understood

**Comment by dimauromattia** [comment]
Hi Giacomo, Can you add also the config.yaml file that you are using?

**Comment by principe91** [comment]
It gives me problem in uploading a file. Here the content of the config file:

binning:
  binsperdec: 3
  binsz: 0.1
  roiwidth: 10
data:
  evfile: /nfs/farm/g/glast/g/catalog/P8_P302/P8_P302_8years_zmax105.lst
  ltcube: null
  scfile: /nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/ft2_8years.lst
fileio:
  logfile: /nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/3FHL/J1825_new_1GeV_new/fermipy.log
  outdir: /nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/3FHL/J1825_new_1GeV_new/
  scratchdir: /scratch
  usescratch: false
gtlike:
  edisp: true
  edisp_disable:
  - galdiff
  - isodiff
  irfs: P8R2_SOURCE_V6
model:
  catalogs: /nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/gll_psc_8year_v5.fit
  extdir: /u/gl/mdwood/fermi/catalogs/Extended_archive_v18
  galdiff: /afs/slac/g/glast/groups/diffuse/rings/4year/preliminary/template_4years_P8_V2_scaled.fits
  isodiff: /u/gl/majello/ki06/P8_100GeV/Scripts/isotropic_source_4years_P8V3_extended.txt
  sources:
  - Scale: 1000
    SpatialModel: RadialDisk
    SpatialWidth: 1.05
    SpectrumType: LogParabola
    beta: 0.0
    dec: -13.992
    name: HESS-J1825
    norm: 1.0e-11
    ra: 276.296
  src_roiwidth: 14.0
selection:
  dec: -13.992
  emax: 1000000
  emin: 1000
  evclass: 128
  evtype: 3
  filter: null
  glat: null
  glon: null
  ra: 276.296
  target: null
  tmax: null
  tmin: null
  zmax: 105

**Comment by cdeil** [comment]
Is this with Astropy 1.2, i.e. same issue as #203 ?

**Comment by principe91** [comment]
Yes, I'm using the version u'1.2.1'. Thanks I will try with a new version.

**Comment by dimauromattia** [comment]
Hi Giacomo, I checked that gta.setup is working correctly with your config.yaml file. I am using Astropy 2.0.4. You can find the output here /nfs/slac/kipac/fs1/u/mdimauro/workdir/fermipydev/try_giacomo . Please close the issue if you think it is fixed.
