### ISSUE TITLE
Issue with gta.set_source_spectrum with PowerLaw

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/fermipy#213]
I am encountering an issue with gta.set_source_spectrum.
In particular I find that if I have a source that is a PowerLaw in the model and I change its SED shape into a Log Parabola everything works smoothly:

PL:
 idx parname                  value     error       min       max     scale free
--------------------------------------------------------------------------------
3FGL J0029.1-7045
   4 Prefactor                0.469    0.0589     1e-05     1e+03     1e-12    *
   5 Index                     2.34     0.109         0         5        -1    *
   6 Scale                 1.26e+03         0  1.26e+03  1.26e+03         1     
LP
3FGL J0029.1-7045
   4 norm                     0.469         0     1e-05     1e+03     1e-12    *
   5 alpha                     2.34         0         0         5         1     
   6 beta                         0         0         0         1         1     
   7 Eb                    1.26e+03         0  1.26e+03  1.26e+03         1     

The bounds and scale are well defined.
However if I try to changed the SED from LogParabola to PowerLaw I find:

In [18]: gta.set_source_spectrum('3FGL J0029.1-7045','PowerLaw')
/u/gl/mdimauro/kipac/software/anaconda/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py:226: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)
3FGL J0029.1-7045
   4 Prefactor                    1         0  -3.4e+38   3.4e+38         1    *
   5 Index                       -2         0  -3.4e+38   3.4e+38         1    *
   6 Scale                        1         0  -3.4e+38   3.4e+38         1     

and If I try to make a fit it print errors:

In [20]: gta.fit()
2018-03-24 16:04:19 INFO    GTAnalysis.fit(): Starting fit.
2018-03-24 16:04:21 ERROR   GTAnalysis._fit_optimizer(): Likelihood optimization failed.
Traceback (most recent call last):
  File "/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.py", line 2842, in _fit_optimizer
    self.like.fit(**kw)
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-07-00/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject, numericDerivs=numericDerivs)
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-07-00/python/SummedLikelihood.py", line 196, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-07-00/python/pyLikelihood.py", line 2792, in find_min
    return _pyLikelihood.Minuit_find_min(*args)
RuntimeError: Attempt to set the value outside of existing bounds.
2018-03-24 16:04:21 ERROR   GTAnalysis._fit_optimizer(): Likelihood optimization failed.
Traceback (most recent call last):
  File "/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.py", line 2842, in _fit_optimizer
    self.like.fit(**kw)
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-07-00/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject, numericDerivs=numericDerivs)
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-07-00/python/SummedLikelihood.py", line 196, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-07-00/python/pyLikelihood.py", line 2792, in find_min
    return _pyLikelihood.Minuit_find_min(*args)
RuntimeError: Attempt to set the value outside of existing bounds.
2018-03-24 16:04:21 ERROR   GTAnalysis._fit_optimizer(): Likelihood optimization failed.
Traceback (most recent call last):
  File "/nfs/slac/kipac/fs1/u/mdimauro/software/fermipy/fermipy/gtanalysis.py", line 2842, in _fit_optimizer
    self.like.fit(**kw)
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-07-00/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject, numericDerivs=numericDerivs)
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-07-00/python/SummedLikelihood.py", line 196, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "/nfs/farm/g/glast/u35/ReleaseManagerBuild/redhat6-x86_64-64bit-gcc44/Optimized/ScienceTools/11-07-00/python/pyLikelihood.py", line 2792, in find_min
    return _pyLikelihood.Minuit_find_min(*args)
RuntimeError: Attempt to set the value outside of existing bounds.
2018-03-24 16:04:21 ERROR   GTAnalysis.fit(): MINUIT failed with status code 1 fit quality 0

The issue is probably due to the bounds of the SED parameters that are put to -3.4e+38   3.4e+38 and also to the value given to the prefactor and scale.
I will give a look to the code.

Cheers

**Comment by dimauromattia** [comment]
I am finding the same error also if I change the SED into the 'PLSuperExpCutoff'

In [4]: gta.set_source_spectrum('3FGL J0023.9-7203','PLSuperExpCutoff')
/u/gl/mdimauro/kipac/software/anaconda/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py:226: UserWarning: 
A theoretically impossible result was found during the iteration
process for finding a smoothing spline with fp = s: s too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)
Failed to create spline:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [3.14981472e+15 3.14981472e+15 3.14981472e+15 3.14981472e+15
 3.14981472e+15 3.14981472e+15 3.14981472e+15 3.14981472e+15
 3.14981472e+15 3.14981472e+15 3.14981472e+15 3.14981472e+15
 3.14981472e+15 3.14981472e+15 3.14981472e+15 3.14981472e+15
 3.14981472e+15 3.14981472e+15 3.14981472e+15 3.14981472e+15]
Failed to create spline:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [3.14981472e+15 3.14981472e+15 3.14981472e+15 3.14981472e+15
 3.14981472e+15 3.14981472e+15 3.14981472e+15 3.14981472e+15
 3.14981472e+15 3.14981472e+15 3.14981472e+15 3.14981472e+15
 3.14981472e+15 3.14981472e+15 3.14981472e+15 3.14981472e+15
 3.14981472e+15 3.14981472e+15 3.14981472e+15 3.14981472e+15]

In [5]: gta.print_params()
2018-03-24 16:26:38 INFO    GTAnalysis.print_params(): 
 idx parname                  value     error       min       max     scale free
--------------------------------------------------------------------------------
3FGL J0021.6-6835
   0 Prefactor                 2.45      2.31     1e-05     1e+03     1e-12    *
   1 Index                     3.41     0.819         0         5        -1    *
   2 Scale                      533         0       533       533         1     
3FGL J0023.9-7203
   3 Prefactor                   10         0  -3.4e+38   3.4e+38         1    *
   4 Index1                    -2.1         0  -3.4e+38   3.4e+38         1    *
   5 Scale                    1e+03         0  -3.4e+38   3.4e+38         1     
   6 Cutoff                   1e+04         0  -3.4e+38   3.4e+38         1    *
   7 Index2                       2         0  -3.4e+38   3.4e+38         1    *

**Comment by Time-Cheung** [comment]
Hello, I'm encountering the same problem when the spectrum of the source in the model is PowerlLaw, could you tell me how did solve it? Thanks a lot!
