### ISSUE TITLE
pylikelihood and Minuit errors

### ISSUE THREAD

**Issue by rangioni** [fermiPy/fermipy#217]
I got this error while performing a likelihood fit as part of my own light curve scripts:

Traceback (most recent call last):
 File "/data1/users/fermi/3c264/daily/LC/lc8/like_for_LC.py", line 17, in <module>
   gta.setup(overwrite=False)
 File "/cluster/fermi/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1023, in setup
   self._create_likelihood()
 File "/cluster/fermi/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1053, in _create_likelihood
   self._init_roi_model()
 File "/cluster/fermi/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1075, in _init_roi_model
   rm['components'][i]['loglike'] = -c.like()
 File "/cluster/fermi/fermitools/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.17-without-root/x86_64-unknown-linux-gnu-libc2.17/lib/python/AnalysisBase.py", line 73, in __call__
   return -self.logLike.value()
 File "/cluster/fermi/fermitools/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.17-without-root/x86_64-unknown-linux-gnu-libc2.17/lib/python/pyLikelihood.py", line 6159, in value
   return lib_pyLikelihood.BinnedLikelihood_value(*args)
RuntimeError: vector::_M_range_check

I then updated the Science tools to the latest version, and got a different error message:

2018-04-24 11:45:37 ERROR   GTAnalysis._fit_optimizer(): Likelihood optimization failed.
Traceback (most recent call last):
  File "/cluster/fermi/miniconda/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2694, in _fit_optimizer
    self.like.fit(**kw)
  File "/cluster/fermi/fermitools/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.17/x86_64-unknown-linux-gnu-libc2.17/lib/python/SummedLikelihood.py", line 95, in fit
    optObject=optObject)
  File "/cluster/fermi/fermitools/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.17/x86_64-unknown-linux-gnu-libc2.17/lib/python/SummedLikelihood.py", line 194, in _errors
    myOpt.find_min(verbosity, tol, self.tolType)
  File "/cluster/fermi/fermitools/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.17/x86_64-unknown-linux-gnu-libc2.17/lib/python/pyLikelihood.py", line 2784, in find_min
    return lib_pyLikelihood.Minuit_find_min(*args)
RuntimeError: Attempt to set the value outside of existing bounds.

I tried to modify the bounds of the free parameter in the fit, but it didn't solve the problem. This only happens in a couple of time intervals, in others the analysis did not give me any problems even with the outdated version of the STs.

**Comment by dimauromattia** [comment]
Hi Roberto,

Can you give us more informations on the analysis that you are running? If it is possible, Could you send the configuration file, script, dataset you are using. In this way it will be easier to fix the problem.
Thanks

Mattia

**Comment by rangioni** [comment]
Hi Mattia,
I am attaching a zip with the analysis folder in question, including the configuration file (config.yaml), script (like_for_LC.py), and all the rest of the files, including the logs. Some context: this is a script to perform a likelihood in a light curve bin, as part of my own light curve scripts with Fermipy. In this specific case, the data is in daily bins.

[lc8.zip](https://github.com/fermiPy/fermipy/files/1954469/lc8.zip)

**Comment by dimauromattia** [comment]
Hi @rangioni ,
I suspect this problem has something to do with the short time range required by the analysis (1 day). I checked the time and energy range of the files and everything seems to be in order. The message "RuntimeError: Attempt to set the value outside of existing bounds." can be due to very faint sources that are difficult to fit and by many other reasons. I suggest to try to make the fit in a much larger time scale and see if you still find the error.
