### ISSUE TITLE
Error 'data type not understood'

### ISSUE THREAD

**Issue by vaidehiratna** [fermiPy/fermipy#236]
Since I updated fermiPy to latest version (v 0.17) using anaconda, my jobs have started getting crashed in SLAC. Interestingly, this does not happen every time. It appears like the issue is with some particular nodes where jobs went after submission. Before running the job, I declare the following two paths:

export CONDABASE=/u/gl/vaidehi/fermi_disk/anaconda_installation
export CALDB=/afs/slac/g/glast/groups/canda/irfs/p8_merit/P8R3_V2/CALDB

Below is the full error.

... lots of lines ......
2018-06-06 15:40:27 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for isodiff....................!
2018-06-06 15:40:27 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 790.84 s
2018-06-06 15:40:27 INFO    GTBinnedAnalysis.setup(): Finished setup for component 02
2018-06-06 15:40:27 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
2018-06-06 15:40:33 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 01.
2018-06-06 15:40:38 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 02.

Traceback (most recent call last):
  File "/u/gl/vaidehi/HIGH_Z_QUASARS/NO_FL8Y1.py", line 262, in <module>
    main(sys.argv)
  File "/u/gl/vaidehi/HIGH_Z_QUASARS/NO_FL8Y1.py", line 131, in main
    gta.setup()
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.17.1+2.gfc75-py2.7.egg/fermipy/gtanalysis.py", line 1042, in setup
    self._create_likelihood()
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.17.1+2.gfc75-py2.7.egg/fermipy/gtanalysis.py", line 1072, in _create_likelihood
    self._init_roi_model()
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.17.1+2.gfc75-py2.7.egg/fermipy/gtanalysis.py", line 1107, in _init_roi_model
    self._coadd_maps(cmaps, shape, rm, wmaps)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/fermipy-0.17.1+2.gfc75-py2.7.egg/fermipy/gtanalysis.py", line 3931, in _coadd_maps
    self._ccube.write(self.files['ccube'], conv='fgst-ccube')
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/gammapy-0.7-py2.7-linux-x86_64.egg/gammapy/maps/base.py", line 266, in write
    hdulist = self.to_hdulist(**kwargs)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/gammapy-0.7-py2.7-linux-x86_64.egg/gammapy/maps/wcsmap.py", line 158, in to_hdulist
    conv=conv)
  File "/u/gl/vaidehi/.local/lib/python2.7/site-packages/gammapy-0.7-py2.7-linux-x86_64.egg/gammapy/maps/geom.py", line 963, in make_bands_hdu
    return fits.BinTableHDU.from_columns(cols, header, name=hdu)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/io/fits/hdu/table.py", line 126, in from_columns
    data = FITS_rec.from_columns(coldefs, nrows=nrows, fill=fill)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 342, in from_columns
    raw_data = np.empty(columns.dtype.itemsize * nrows, dtype=np.uint8)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/utils/decorators.py", line 498, in __get__
    val = self.fget(obj)
  File "/afs/slac/g/glast/ground/GLAST_EXT/redhat6-x86_64-64bit-gcc44/python/2.7.12-anaconda2-4.2.0/lib/python2.7/site-packages/astropy/io/fits/column.py", line 1435, in dtype
    return nh.realign_dtype(np.dtype(fields), offsets)
TypeError: data type not understood

**Comment by dimauromattia** [comment]
Hi @vaidehiratna ,
From to the error it looks like your area takes python from /u/gl/vaidehi/.local/lib/python2.7 and not from your anaconda path (/u/gl/vaidehi/fermi_disk/anaconda_installation). Usually this could be fixed deleting your .local folder.

**Comment by vaidehiratna** [comment]
Yep. It worked. Thanks.
