### ISSUE TITLE
Extension fitting with PSF sub-types

### ISSUE THREAD

**Issue by zimmerst** [fermiPy/fermipy#248]
This is going to be a stub and mostly a reminder. When running the gta.extension() method on my PSF-subtype analysis with **fermipy-0.17.3+17.g6cbb** I get the following stack trace:

```python
Traceback (most recent call last):
  File "ngc4839_ext.py", line 15, in <module>
    ext_gauss = gta.extension('FL8Y J1256.6+2741')
  File "/nfs/farm/g/glast/u/zimmer/software/fermipy/fermipy/extension.py", line 73, in extension
    ext = self._extension(name, **config)
  File "/nfs/farm/g/glast/u/zimmer/software/fermipy/fermipy/extension.py", line 192, in _extension
    psf_scale_fn=psf_scale_fn)
  File "/nfs/farm/g/glast/u/zimmer/software/fermipy/fermipy/extension.py", line 560, in _fit_extension
    reoptimize=reoptimize)
  File "/nfs/farm/g/glast/u/zimmer/software/fermipy/fermipy/extension.py", line 413, in _scan_extension
    loglike = self._scan_extension_fast(name, **kwargs)
  File "/nfs/farm/g/glast/u/zimmer/software/fermipy/fermipy/extension.py", line 443, in _scan_extension_fast
    psf_scale_fn=psf_scale_fn)
  File "/nfs/farm/g/glast/u/zimmer/software/fermipy/fermipy/gtanalysis.py", line 680, in set_source_morphology
    self._update_srcmap(src.name, src, psf_scale_fn=psf_scale_fn)
  File "/nfs/farm/g/glast/u/zimmer/software/fermipy/fermipy/gtanalysis.py", line 610, in _update_srcmap
    c._update_srcmap(name, src, **kwargs)
  File "/nfs/farm/g/glast/u/zimmer/software/fermipy/fermipy/gtanalysis.py", line 5570, in _update_srcmap
    k = self._create_srcmap(name, src, **kwargs)
  File "/nfs/farm/g/glast/u/zimmer/software/fermipy/fermipy/gtanalysis.py", line 5552, in _create_srcmap
    exp = self._bexp.interp_by_coord(
AttributeError: 'GTBinnedAnalysis' object has no attribute '_bexp'
```

**Comment by zimmerst** [comment]
In this regard, in my original ROI model, I am modeling the source in question as point source, but for the extension fitting i'm changing the model to a *RadialGaussian*. Could this be the source of the culprit?

**Comment by dimauromattia** [comment]
Hi Stephan.
If I understand correctly you have the source with a RadialGaussian template before running gta.extension. Right? If this is the case, can you try to rerun the analysis with a point-like source? Do you have the same error if you run the analysis with a unique PSF component?

**Comment by zimmerst** [comment]
Hi Mattia,
nope, i start with the source being a point-like source. But when calling gta.extension() I need to specify some baseline template (even if this is a RadialGaussian by default). I will try to re-run the gta.extension() analysis with only one PSF component to see what happens.

**Comment by zimmerst** [comment]
I think this is a residual effect from removing sources programmatically from the ROI. To be tested, but here's a minimal example:

gta.delete_sources(['sourceA','sourceB'])
gta.extension('sourceC') 

should yield the above error. Will update this post later.

**Comment by lemoinema** [comment]
Hi all,
Did someone found out how to solve this issue. I encounter the same crash 'GTBinnedAnalysis' object has no attribute '_bexp' when doing 
loc = gta.localize('srcname', free_background=True, free_radius=1.0, make_plots=True) with multiple PSF types.
Thanks,
Marianne

**Comment by emmaow** [comment]
Dear all,

any advance on this thread? I am using the latest fermipy and try to run the extension and still get an error: "AttributeError: 'GTBinnedAnalysis' object has no attribute '_bexp'"
I tried point source, radial gaussian or radial disk, and nothing changed. Also, I am not using several PSF sub-types. Is there any solution to this? 
Thanks
Emma

**Comment by eacharles** [comment]
Ok.   I've improved the error that you get when gta._bexp is not set.
