### ISSUE TITLE
TypeError: write() got an unexpected keyword argument 'overwrite'

### ISSUE THREAD

**Issue by imereu** [fermiPy/fermipy#265]
When I try to do the lightcurve I find this error:
Traceback (most recent call last):
  File "runlc.py", line 48, in <module>
    main()
  File "runlc.py", line 38, in main
    lc = gta.lightcurve('Source', free_radius=3.0)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/fermipy/lightcurve.py", line 287, in lightcurve
    o = self._make_lc(name, **config)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/fermipy/lightcurve.py", line 433, in _make_lc
    mapo = p.map(wrap, itimes)
  File "/home/ubuntu/miniconda/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/ubuntu/miniconda/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: write() got an unexpected keyword argument 'overwrite'
[1]+  Exit 1                  nohup python runlc.py

**Comment by dimauromattia** [comment]
Hi @imereu, what version of Fermipy are you using?

**Comment by imereu** [comment]
0.17.3+57

**Comment by imereu** [comment]
I have updated fermipy and now I try my analysis again.

**Comment by imereu** [comment]
Now it seems to work. I have update fermipy using
pip install git+https://github.com/fermiPy/fermipy.git
If I use
conda update fermipy
the analysis doesn't work

**Comment by dimauromattia** [comment]
Hi @imereu, The latest version of Fermipy we have in github is not updated in conda yet. We will release soon a new public release.
