### ISSUE TITLE
ImportError: libicui18n.so.56 after updating fermiPy

### ISSUE THREAD

**Issue by astro-fermi** [fermiPy/fermipy#270]
Hi,

I just updated fermiPy in SLAC using the following command: 
conda update fermipy

while updating many packages, it also showed to downgrade a few:

The following packages will be DOWNGRADED:
    fontconfig:      2.12.6-0              conda-forge --> 2.12.1-1              conda-forge
    freetype:        2.8.1-0               conda-forge --> 2.6.3-1               conda-forge
    matplotlib:      2.2.2-py27_1          conda-forge --> 2.0.0b1-np111py27_2   conda-forge
    numpy:           1.14.5-py27hcd700cb_0             --> 1.11.3-py27h3dfced4_4            
    pyqt:            5.6.0-py27_5          conda-forge --> 4.11.4-py27_3         conda-forge
    qt:              5.6.2-7               conda-forge --> 4.8.7-2                          

The up-gradation went successful. However, when I tested whether all is well by running the following command:
from fermipy.gtanalysis import GTAnalysis

I get the following error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/gl/vaidehi/fermi_disk/anaconda_installation/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 24, in <module>
    import fermipy.plotting as plotting
  File "/u/gl/vaidehi/fermi_disk/anaconda_installation/lib/python2.7/site-packages/fermipy/plotting.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/u/gl/vaidehi/fermi_disk/anaconda_installation/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/u/gl/vaidehi/fermi_disk/anaconda_installation/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/u/gl/vaidehi/fermi_disk/anaconda_installation/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/u/gl/vaidehi/fermi_disk/anaconda_installation/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/u/gl/vaidehi/fermi_disk/anaconda_installation/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/u/gl/vaidehi/fermi_disk/anaconda_installation/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

When I run the command 'which python', I get the following output
~/fermi_disk/anaconda_installation/bin/python

Please help.

Thanks.

**Comment by astro-fermi** [comment]
I just installed anaconda + fermiPy from scratch and it is working OK. Will report if see any other problem.
