### ISSUE TITLE
light curve error

### ISSUE THREAD

**Issue by basuparth** [fermiPy/fermipy#275]
I was trying to generate the light curve when I ran into the following error after running successfully for quite a few bins(10 of 20). Also there was no resulting lightcurve.fits file with the data from the successful bins. Is there a way to work around this by skipping the unsuccessful bin and completing the rest of the process? Thanks for the help
fermipy version = latest
fermi version = 1.0.0 in anaconda
error report

2019-03-25 19:40:53 INFO    lightcurve_543110400_543456000 GTBinnedAnalysis._create_ltcube(): Generating local LT cube.
/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:351: RuntimeWarning: divide by zero encountered in log
  np.log(self._psf),
/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:355: RuntimeWarning: divide by zero encountered in log
  np.log(self._wts),
Analysis failed in time range 543110400 543456000
<type 'exceptions.RuntimeError'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/lightcurve.py", line 290, in lightcurve
    o = self._make_lc(name, **config)
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/lightcurve.py", line 439, in _make_lc
    mapo = map(wrap, itimes)
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/lightcurve.py", line 158, in _process_lc_bin
    gta.setup()
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1051, in setup
    self._create_likelihood()
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1076, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 5312, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 65, in __init__
    pyLike.AppHelpers_checkExposureMap(srcMaps, binnedExpMap)
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 4899, in AppHelpers_checkExposureMap
    return _pyLikelihood.AppHelpers_checkExposureMap(cmapfile, emapfile)
RuntimeError: File not found: /home/parth/SINP/fermipy/1ES1218+304new/lightcurve_543110400_543456000/srcmap_00.fits

**Comment by jefemagril** [comment]
It looks like gtsrcmap may have failed in that bin for some reason. Can you go into that directory and confirm that srcmap_00.fits file does not exist?

**Comment by basuparth** [comment]
@jefemagril yes the srcmap_00.fits is missing.

**Comment by jefemagril** [comment]
Ok I don't know why it failed in only 1 bin, that is odd to me. Is there any chance you could check the logs for that bin to see if there was an earlier error for the gtsrcmap? There should be a log file in every bin's directory if I'm not mistaken.

**Comment by basuparth** [comment]
while running the gtsrcmap there was a core dumped message and the sourcemaps were never generated

the relevant section of the log file

2019-03-26 01:14:49 DEBUG   lightcurve_543110400_543456000 GTBinnedAnalysis.run_gtapp(): This is gtsrcmaps version HEAD
2019-03-26 01:14:49 DEBUG   lightcurve_543110400_543456000 GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
2019-03-26 01:14:49 DEBUG   lightcurve_543110400_543456000 GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R3_SOURCE_V2
2019-03-26 01:14:49 DEBUG   lightcurve_543110400_543456000 GTBinnedAnalysis.run_gtapp(): event_types:  0  1
2019-03-26 01:14:49 DEBUG   lightcurve_543110400_543456000 GTBinnedAnalysis.run_gtapp(): Floating point exception (core dumped)
2019-03-26 01:14:49 DEBUG   lightcurve_543110400_543456000 GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 7.94 s

**Comment by basuparth** [comment]
Update: I tried making an aperture lightcurve by following the fermi tutorial and found that for the bin where fermipy fails there are no fluxpoints. Is this an error from Fermi or something else ? Normally in fermipy if some bin fails fermipy goes on to the next bin and completes the analysis with an end report mentioning the 2,3 failed bins but for some reason in this particular case the entire process terminates with the failed bin.
![Aperture_LC](https://user-images.githubusercontent.com/47746249/55272365-9f956c80-52e1-11e9-825e-cb00bacdf50a.png)

**Comment by dimauromattia** [comment]
Hi @basuparth, When the analysis fails in one bin Fermipy continues the analysis going to the next bin. When the analysis is completed in all time bins, the bins where the analysis failed are not considered in the calculation of the TS of variability. You can find the bins where the analysis failed by looking to the output parameter fit_success. Best

**Comment by basuparth** [comment]
Hi @dimauromattia , just as you say I normally get Fermipy proceeding to the next bin but for the reported time period of the analysis my lightcurve analysis terminated. Incidentally the bin where the lightcurve analysis failed(I found out later) corresponds with the duration when fermi temporarily shutdown due to solar panel issues. Perhaps the availability of no photons leads to this error. 

I was also running a rough analysis of a GRB with fermipy. After adding it as a source I was able to get the sed but then during the lightcurve analysis I got a failed bin down the way after which the entire analysis was aborted without yielding any lightcurve.fits/npy file.

**Entire Analysis Report of the lc analysis.**

>>> lc = gta.lightcurve('GRB190114C', nbins=5)
2019-04-05 11:38:12 INFO    GTAnalysis.lightcurve(): Computing Lightcurve for GRB190114C
2019-04-05 11:38:13 INFO    lightcurve_569191700_569191912 GTAnalysis._process_lc_bin(): Fitting time range 569191700 569191912
2019-04-05 11:38:15 INFO    lightcurve_569191700_569191912 GTBinnedAnalysis._create_ltcube(): Generating local LT cube.
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
WARNING: FITSFixedWarning: 'datfix' made the change 'Invalid parameter value: invalid date '        ''. [astropy.wcs.wcs]
2019-04-05 11:44:50 INFO    lightcurve_569191700_569191912 GTBinnedAnalysis.write_xml(): Writing /home/parth/SINP/fermipy/GRB190114C/lightcurve_569191700_569191912/base_00.xml...
Joint fit  ['GRB190114C', '4FGL J0338.9-2848', '4FGL J0348.5-2749']
2019-04-05 11:44:53 INFO    lightcurve_569191700_569191912 GTBinnedAnalysis.write_xml(): Writing /home/parth/SINP/fermipy/GRB190114C/lightcurve_569191700_569191912/fit_model_final_00.xml...
2019-04-05 11:44:54 INFO    lightcurve_569191700_569191912 GTAnalysis._process_lc_bin(): Finished time range 569191700 569191912
2019-04-05 11:44:56 INFO    lightcurve_569191912_569192124 GTAnalysis._process_lc_bin(): Fitting time range 569191912 569192124
2019-04-05 11:45:02 INFO    lightcurve_569191912_569192124 GTBinnedAnalysis._create_ltcube(): Generating local LT cube.
2019-04-05 11:52:34 INFO    lightcurve_569191912_569192124 GTBinnedAnalysis.write_xml(): Writing /home/parth/SINP/fermipy/GRB190114C/lightcurve_569191912_569192124/base_00.xml...
Joint fit  ['GRB190114C', '4FGL J0338.9-2848', '4FGL J0348.5-2749']
2019-04-05 11:52:36 INFO    lightcurve_569191912_569192124 GTBinnedAnalysis.write_xml(): Writing /home/parth/SINP/fermipy/GRB190114C/lightcurve_569191912_569192124/fit_model_final_00.xml...
2019-04-05 11:52:38 INFO    lightcurve_569191912_569192124 GTAnalysis._process_lc_bin(): Finished time range 569191912 569192124
2019-04-05 11:52:39 INFO    lightcurve_569192124_569192336 GTAnalysis._process_lc_bin(): Fitting time range 569192124 569192336
2019-04-05 11:52:44 INFO    lightcurve_569192124_569192336 GTBinnedAnalysis._create_ltcube(): Generating local LT cube.
2019-04-05 12:03:14 INFO    lightcurve_569192124_569192336 GTBinnedAnalysis.write_xml(): Writing /home/parth/SINP/fermipy/GRB190114C/lightcurve_569192124_569192336/base_00.xml...
Joint fit  ['GRB190114C', '4FGL J0338.9-2848', '4FGL J0348.5-2749']
Fitting shape GRB190114C TS:    833.074
Fitting shape 4FGL J0338.9-2848 TS:     17.525
/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/scipy/interpolate/fitpack2.py:224: UserWarning: 
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)
2019-04-05 12:03:20 INFO    lightcurve_569192124_569192336 GTBinnedAnalysis.write_xml(): Writing /home/parth/SINP/fermipy/GRB190114C/lightcurve_569192124_569192336/fit_model_final_00.xml...
2019-04-05 12:03:23 INFO    lightcurve_569192124_569192336 GTAnalysis._process_lc_bin(): Finished time range 569192124 569192336
2019-04-05 12:03:25 INFO    lightcurve_569192336_569192548 GTAnalysis._process_lc_bin(): Fitting time range 569192336 569192548
2019-04-05 12:03:30 INFO    lightcurve_569192336_569192548 GTBinnedAnalysis._create_ltcube(): Generating local LT cube.
Analysis failed in time range 569192336 569192548
<type 'exceptions.RuntimeError'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermipy/lightcurve.py", line 290, in lightcurve
    o = self._make_lc(name, **config)
  File "/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermipy/lightcurve.py", line 439, in _make_lc
    mapo = map(wrap, itimes)
  File "/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermipy/lightcurve.py", line 158, in _process_lc_bin
    gta.setup()
  File "/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1051, in setup
    self._create_likelihood()
  File "/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1076, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 5312, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 74, in __init__
    self._createObservation(srcMaps, expCube, self.irfs)
  File "/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 77, in _createObservation
    self._respFuncs.load_with_event_types(irfs, "", self.srcMaps, "")
  File "/home/parth/anaconda2/envs/fermi1/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 8132, in load_with_event_types
    return _pyLikelihood.ResponseFunctions_load_with_event_types(self, respFuncs, respBase, filename, extname)
RuntimeError: Cannot read keyword "NDSKEYS" in file "/home/parth/SINP/fermipy/GRB190114C/lightcurve_569192336_569192548/srcmap_00.fits" (CFITSIO ERROR 202: keyword not found in header)
[fermipy.log](https://github.com/fermiPy/fermipy/files/3046662/fermipy.log)
