### ISSUE TITLE
lightcurve analysis terminated after one failed bin

### ISSUE THREAD

**Issue by basuparth** [fermiPy/fermipy#280]
I was analyzing a source for ~1year period data with weekly binning when the entire analysis terminated after one failed bin.  I had also reported a similar error prior to this but in that case, there had been an issue with the fermi solar panel drives for a portion of the data(but even then one would expect that the analysis would go on after reporting the failed bins). It seems that the fermipy lightcurve analysis continuation after a failed bin is dependent on the type of error actually encountered. If the error is due to the fit not converging then the analysis goes on but in some other cases, the entire analysis is terminated without producing any results even for the prior successful bins. It would be a great help if you could please have a look into this. Also, I analyzed this same data with monthly binning and I got my lightcurve.

Error report

2019-04-07 18:50:07 INFO    lightcurve_560069225_560674025 GTAnalysis._process_lc_bin(): Finished time range 560069225 560674025
2019-04-07 18:50:09 INFO    lightcurve_560674025_561278825 GTAnalysis._process_lc_bin(): Fitting time range 560674025 561278825
2019-04-07 18:50:14 INFO    lightcurve_560674025_561278825 GTBinnedAnalysis._create_ltcube(): Generating local LT cube.
/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:351: RuntimeWarning: divide by zero encountered in log
  np.log(self._psf),
/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:355: RuntimeWarning: divide by zero encountered in log
  np.log(self._wts),
Analysis failed in time range 560674025 561278825
<type 'exceptions.RuntimeError'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/lightcurve.py", line 290, in lightcurve
    o = self._make_lc(name, **config)
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/lightcurve.py", line 439, in _make_lc
    mapo = map(wrap, itimes)
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/lightcurve.py", line 158, in _process_lc_bin
    gta.setup()
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1051, in setup
    self._create_likelihood()
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1076, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 5312, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 65, in __init__
    pyLike.AppHelpers_checkExposureMap(srcMaps, binnedExpMap)
  File "/home/parth/anaconda2/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 4899, in AppHelpers_checkExposureMap
    return _pyLikelihood.AppHelpers_checkExposureMap(cmapfile, emapfile)
RuntimeError: File not found: /home/parth/SINP/1ES1218+304n/lightcurve_560674025_561278825/srcmap_00.fits

**Comment by dimauromattia** [comment]
Hello @basuparth, Can you send me the script and the configuration you are using? I need to rerun your same analysis to fix this issue.

**Comment by basuparth** [comment]
[config.txt](https://github.com/fermiPy/fermipy/files/3196606/config.txt)
[fermipy_analyser.txt](https://github.com/fermiPy/fermipy/files/3196625/fermipy_analyser.txt)
Hi @dimauromattia. Please find the config file and analysis script attached.

**Comment by eacharles** [comment]
The gta.setup() in process LC bin is in a try block, but we were not recovering gracefully from this.
I've updated the code to recover gracefully.
