### ISSUE TITLE
Error in extension fitting

### ISSUE THREAD

**Issue by damgreen** [fermiPy/fermipy#342]
I'm attempting to measure the extension of source with a RadialGaussian with fit_position=True and I get the error posted below.  I'm using v 0.19.0. This doesn't happen in v0.18.1.  This also doesn't happen when fit_position=False.  Tracing the error it is something to do with _fit_position from sourcefind.py which is used in _fit_extension_full from extension.py and no where else. I could't find any recent changes to sourcefind.py that would account for this. My only idea is it has something to do with the rectangular ROI recently implemented.  I tried with different width_nstep and the same error just with different numbers.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-e547ceabaa20> in <module>()
      2 gta.free_source(psr_name)
      3 gta.free_source(pwn_name)
----> 4 ext_gauss_free = gta.extension(pwn_name,spatial_model='RadialGaussian',free_background=True,fit_position=True,update=False,make_plots=True)

/Users/david/fermipy/fermipy/extension.pyc in extension(self, name, **kwargs)
     71 
     72         free_state = FreeParameterState(self)
---> 73         ext = self._extension(name, **config)
     74         free_state.restore()
     75 

/Users/david/fermipy/fermipy/extension.pyc in _extension(self, name, **kwargs)
    186             ext_fit = self._fit_extension_full(name,
    187                                                spatial_model=spatial_model,
--> 188                                                optimizer=kwargs['optimizer'])
    189         else:
    190             ext_fit = self._fit_extension(name,

/Users/david/fermipy/fermipy/extension.pyc in _fit_extension_full(self, name, **kwargs)
    665             fit_pos0, fit_pos1 = self._fit_position(name, nstep=nstep,
    666                                                     dtheta_max=dtheta_max,
--> 667                                                     zmin=-3.0, use_pylike=False)
    668             o.update(fit_pos0)
    669             t1.stop()

/Users/david/fermipy/fermipy/sourcefind.pyc in _fit_position(self, name, **kwargs)
    495         dtheta_max = kwargs.setdefault('dtheta_max', 0.5)
    496         nstep = kwargs.setdefault('nstep', 5)
--> 497         fit0 = self._fit_position_tsmap(name, **kwargs)
    498 
    499         if np.isfinite(fit0['pos_r68']):

/Users/david/fermipy/fermipy/sourcefind.pyc in _fit_position_tsmap(self, name, **kwargs)
    538                                exclude=[name],
    539                                use_pylike=kwargs.get('use_pylike', True),
--> 540                                make_plots=False, **kw)
    541         else:
    542             tsmap = self.tscube(utils.join_strings([prefix, name.lower().replace(' ', '_')]),                                

/Users/david/fermipy/fermipy/tsmap.pyc in tsmap(self, prefix, **kwargs)
    698         self.logger.log(config['loglevel'], 'Generating TS map')
    699 
--> 700         o = self._make_tsmap_fast(prefix, **config)
    701 
    702         if config['make_plots']:

/Users/david/fermipy/fermipy/tsmap.pyc in _make_tsmap_fast(self, prefix, **kwargs)
    929         amp_values = amp_values[yslice, xslice]
    930 
--> 931         ts_map = WcsNDMap(map_geom, ts_values)
    932         sqrt_ts_map = WcsNDMap(map_geom, ts_values**0.5)
    933         npred_map = WcsNDMap(map_geom, amp_values * model_npred)

/anaconda2/envs/fermipy/lib/python2.7/site-packages/gammapy/maps/wcsnd.pyc in __init__(self, geom, data, dtype, meta, unit)
     56             data = self._make_default_data(geom, data_shape, dtype)
     57 
---> 58         super(WcsNDMap, self).__init__(geom, data, meta, unit)
     59 
     60     @staticmethod

/anaconda2/envs/fermipy/lib/python2.7/site-packages/gammapy/maps/base.pyc in __init__(self, geom, data, meta, unit)
     43     def __init__(self, geom, data, meta=None, unit=""):
     44         self.geom = geom
---> 45         self.data = data
     46         self.unit = unit
     47 

/anaconda2/envs/fermipy/lib/python2.7/site-packages/gammapy/maps/base.pyc in data(self, val)
     83             raise ValueError(
     84                 "Shape {!r} does not match map data shape {!r}"
---> 85                 "".format(val.shape, self.geom.data_shape)
     86             )
     87 

ValueError: Shape (18, 19) does not match map data shape (19, 18)

**Comment by Fdepalma** [comment]
I get the same issue with version v0.19.0 with only the RadialGaussian shape. The RadialDisk works fine.
I was able to get some extension evaluated with the same software setup but after some changes in the background sources now it fails everytime.

My error is the following:

Traceback (most recent call last):
  File "fermipy_analysis_v0.15.4.py", line 429, in <module>
    ext0=gta.extension(source_analysis,spatial_model=spatial_model_fpy, update=True, sqrt_ts_threshold=5,fit_position=True,make_plots=False)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/fermipy/extension.py", line 73, in extension
    ext = self._extension(name, **config)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/fermipy/extension.py", line 248, in _extension
    loglevel=logging.DEBUG)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/fermipy/tsmap.py", line 700, in tsmap
    o = self._make_tsmap_fast(prefix, **config)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/fermipy/tsmap.py", line 931, in _make_tsmap_fast
    ts_map = WcsNDMap(map_geom, ts_values)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/gammapy/maps/wcsnd.py", line 58, in __init__
    super(WcsNDMap, self).__init__(geom, data, meta, unit)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/gammapy/maps/base.py", line 45, in __init__
    self.data = data
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/gammapy/maps/base.py", line 85, in data
    "".format(val.shape, self.geom.data_shape)
ValueError: Shape (26, 27) does not match map data shape (27, 26)

**Comment by damgreen** [comment]
I might know what is happening.  In extension.py a `dtheta_max` is being defined by from either the extension or the 99% of the position: https://github.com/fermiPy/fermipy/blob/d54d88432f24a8b6c2fbb329bdd17aad3571e689/fermipy/extension.py#L660-L667

This has the effect of creating a `dtheta_max` of not "round" numbers. In some test code I get a `dtheta_max` = 1.01937373371. If I force to 1.0 and the code is able to run fine.  Not sure why the localizer cannot use not "round" `dtheta_max` numbers but it could be solved by rounding the `dtheta_max` (before passing it to localizer) to the nearest 0.5.

**Comment by damgreen** [comment]
One more test.  I tried a simple localization of a source with a `dtheta_max` = 1.01937373371 and it fails in a similar way.  

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-77c2c9654363> in <module>()
----> 1 gta.localize(pwn_name,dtheta_max = 1.01937373371)

/Users/david/fermipy/fermipy/sourcefind.pyc in localize(self, name, **kwargs)
    282 
    283         free_state = FreeParameterState(self)
--> 284         loc = self._localize(name, **config)
    285         free_state.restore()
    286 

/Users/david/fermipy/fermipy/sourcefind.pyc in _localize(self, name, **kwargs)
    359                                         zmin=-3.0,
    360                                         use_pylike=False,
--> 361                                         tsmap_fitter=tsmap_fitter)
    362 
    363         self.logger.debug('Completed localization with TS Map.\n'

/Users/david/fermipy/fermipy/sourcefind.pyc in _fit_position_tsmap(self, name, **kwargs)
    538                                exclude=[name],
    539                                use_pylike=kwargs.get('use_pylike', True),
--> 540                                make_plots=False, **kw)
    541         else:
    542             tsmap = self.tscube(utils.join_strings([prefix, name.lower().replace(' ', '_')]),                                

/Users/david/fermipy/fermipy/tsmap.pyc in tsmap(self, prefix, **kwargs)
    698         self.logger.log(config['loglevel'], 'Generating TS map')
    699 
--> 700         o = self._make_tsmap_fast(prefix, **config)
    701 
    702         if config['make_plots']:

/Users/david/fermipy/fermipy/tsmap.pyc in _make_tsmap_fast(self, prefix, **kwargs)
    929         amp_values = amp_values[yslice, xslice]
    930 
--> 931         ts_map = WcsNDMap(map_geom, ts_values)
    932         sqrt_ts_map = WcsNDMap(map_geom, ts_values**0.5)
    933         npred_map = WcsNDMap(map_geom, amp_values * model_npred)

/anaconda2/envs/fermipy/lib/python2.7/site-packages/gammapy/maps/wcsnd.pyc in __init__(self, geom, data, dtype, meta, unit)
     56             data = self._make_default_data(geom, data_shape, dtype)
     57 
---> 58         super(WcsNDMap, self).__init__(geom, data, meta, unit)
     59 
     60     @staticmethod

/anaconda2/envs/fermipy/lib/python2.7/site-packages/gammapy/maps/base.pyc in __init__(self, geom, data, meta, unit)
     43     def __init__(self, geom, data, meta=None, unit=""):
     44         self.geom = geom
---> 45         self.data = data
     46         self.unit = unit
     47 

/anaconda2/envs/fermipy/lib/python2.7/site-packages/gammapy/maps/base.pyc in data(self, val)
     83             raise ValueError(
     84                 "Shape {!r} does not match map data shape {!r}"
---> 85                 "".format(val.shape, self.geom.data_shape)
     86             )
     87 

ValueError: Shape (20, 21) does not match map data shape (21, 20)

**Comment by dimauromattia** [comment]
Hello everyone, I am finding exactly the same error. I am using gammapy 0.9.0 and the latest fermipy.

**Comment by damgreen** [comment]
Hey @dimauromattia , 
The stupid work around I am using is to just round the map size to the nearest 0.1. From sourcefind.py:
https://github.com/fermiPy/fermipy/blob/d54d88432f24a8b6c2fbb329bdd17aad3571e689/fermipy/sourcefind.py#L511-L523
I replace line 519 with:

`2.0 * max(np.round(dtheta_max*10.0)/10.0,0.5)`

but I am sure there is a more complicated underlying issue.

**Comment by Fdepalma** [comment]
I still got the same issue even after this change and the change in extension.py (on the rounding of dtheta_max.
`
Traceback (most recent call last):
  File "fermipy_analysis_v0.15.2.py", line 426, in <module>
    ext0=gta.extension(source_analysis,spatial_model=spatial_model_fpy, update=True, sqrt_ts_threshold=5,width_min=0.01,width_max=1.25892541,width_nstep=43, fit_position=True,make_plots=False)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/fermipy/extension.py", line 73, in extension
    ext = self._extension(name, **config)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/fermipy/extension.py", line 248, in _extension
    loglevel=logging.DEBUG)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/fermipy/tsmap.py", line 700, in tsmap
    o = self._make_tsmap_fast(prefix, **config)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/fermipy/tsmap.py", line 931, in _make_tsmap_fast
    ts_map = WcsNDMap(map_geom, ts_values)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/gammapy/maps/wcsnd.py", line 58, in __init__
    super(WcsNDMap, self).__init__(geom, data, meta, unit)
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/gammapy/maps/base.py", line 45, in __init__
    self.data = data
  File "/afs/slac/g/glast/users/fdepalma/anaconda/envs/ft_1_2_23/lib/python2.7/site-packages/gammapy/maps/base.py", line 85, in data
    "".format(val.shape, self.geom.data_shape)
ValueError: Shape (27, 26) does not match map data shape (26, 27)
`

**Comment by Fdepalma** [comment]
I fixed the dtheta_max to 2 in the extension.py file, after another failure I removed all the precalcolated files and started from scratch. The analysis was completed. I'm pretty much puzzled since the only change I made is in a module that is called just at the end of my analysis.
