### ISSUE TITLE
File not found: srcmap_00.fits

### ISSUE THREAD

**Issue by imereu** [fermiPy/fermipy#343]
When i run my script I have this problem:

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/config.py:213: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict = yaml.load(open(config))
2020-05-14 10:12:25 INFO    GTAnalysis.__init__():
--------------------------------------------------------------------------------
fermipy version 0.19.0
ScienceTools version unknown
/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/model_utils.py:59: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  get_function_spec.fndict = yaml.load(open(modelfile))
2020-05-14 10:12:30 INFO    GTAnalysis.print_roi():
name                SpatialModel   SpectrumType     offset        ts       npred
--------------------------------------------------------------------------------
J0121+2602          PointSource    PowerLaw          0.000       nan         nan
isodiff             ConstantValue  FileFunction      -----       nan         nan
galdiff             MapCubeFunctio PowerLaw          -----       nan         nan

2020-05-14 10:12:30 INFO    GTAnalysis.setup(): Running setup.
2020-05-14 10:12:30 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2020-05-14 10:12:30 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
2020-05-14 10:12:30 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtselect infile=/home/ubuntu/shifttransients/2018.fits outfile=/home/ubuntu/curve/J0121+2602/TBIN_115/data/ft1_00.fits ra=20.396999 dec=26.040001 rad=7.57106781187 tmin=543296000.0 tmax=545926000.0 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
2020-05-14 10:18:35 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:18:35 INFO    GTBinnedAnalysis.run_gtapp(): WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
2020-05-14 10:18:35 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:18:35 INFO    GTBinnedAnalysis.run_gtapp(): This is gtselect version HEAD
2020-05-14 10:18:35 INFO    GTBinnedAnalysis.run_gtapp(): Applying filter string: ((EVENT_CLASS&o200) != o0) && ((EVENT_TYPE&o3) != o0) && angsep(RA,DEC,20.396999,26.040001) < 7.571067812 && 100 < ENERGY && ENERGY <= 300000 && 543296000 < TIME && TIME <= 545926000 && 0 < ZENITH_ANGLE && ZENITH_ANGLE <= 90 && gtifilter()
2020-05-14 10:18:35 INFO    GTBinnedAnalysis.run_gtapp(): Done.
2020-05-14 10:18:35 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtselect. Execution time: 365.56 s
2020-05-14 10:18:35 INFO    GTBinnedAnalysis.run_gtapp(): Running gtltcube.
2020-05-14 10:18:35 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtltcube evfile="/home/ubuntu/curve/J0121+2602/TBIN_115/data/ft1_00.fits" evtable="EVENTS" scfile=/home/ubuntu/shifttransients/L20051316174620DF8BB210_SC00.fits sctable="SC_DATA" outfile=/home/ubuntu/curve/J0121+2602/TBIN_115/data/ltcube_00.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=90.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp(): WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp(): Working on file /home/ubuntu/shifttransients/L20051316174620DF8BB210_SC00.fits
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp(): .....................!
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 72.46 s
/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:51: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  log_ratio = np.log(x[xs1] / x[xs0])
/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:52: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return 0.5 * (y[ys0] * x[xs0] + y[ys1] * x[xs1]) * log_ratio
/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:351: RuntimeWarning: divide by zero encountered in log
  np.log(self._psf),
/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:355: RuntimeWarning: divide by zero encountered in log
  np.log(self._wts),
2020-05-14 10:19:49 INFO    GTBinnedAnalysis.run_gtapp(): Running gtbin.
2020-05-14 10:19:49 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtbin evfile=/home/ubuntu/curve/J0121+2602/TBIN_115/data/ft1_00.fits scfile=/home/ubuntu/shifttransients/L20051316174620DF8BB210_SC00.fits outfile=/home/ubuntu/curve/J0121+2602/TBIN_115/data/ccube_00.fits algorithm="ccube" ebinalg="LOG" emin=100.0 emax=300000.0 enumbins=14 ebinfile=NONE tbinalg="LIN" tbinfile=NONE nxpix=40 nypix=40 binsz=0.25 coordsys="CEL" xref=20.396999 yref=26.040001 axisrot=0.0 rafield="RA" decfield="DEC" proj="AIT" hpx_ordering_scheme="RING" hpx_order=3 hpx_ebin=yes hpx_region="" evtable="EVENTS" sctable="SC_DATA" efield="ENERGY" tfield="TIME" chatter=3 clobber=yes debug=no gui=no mode="ql"
2020-05-14 10:19:50 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp(): WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp(): Working on file /home/ubuntu/shifttransients/L20051316174620DF8BB210_SC00.fits
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp(): .....................!
2020-05-14 10:19:48 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 72.46 s
/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:51: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  log_ratio = np.log(x[xs1] / x[xs0])
/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:52: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return 0.5 * (y[ys0] * x[xs0] + y[ys1] * x[xs1]) * log_ratio
/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:351: RuntimeWarning: divide by zero encountered in log
  np.log(self._psf),
/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/irfs.py:355: RuntimeWarning: divide by zero encountered in log
  np.log(self._wts),
2020-05-14 10:19:49 INFO    GTBinnedAnalysis.run_gtapp(): Running gtbin.
2020-05-14 10:19:49 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtbin evfile=/home/ubuntu/curve/J0121+2602/TBIN_115/data/ft1_00.fits scfile=/home/ubuntu/shifttransients/L20051316174620DF8BB210_SC00.fits outfile=/home/ubuntu/curve/J0121+2602/TBIN_115/data/ccube_00.fits algorithm="ccube" ebinalg="LOG" emin=100.0 emax=300000.0 enumbins=14 ebinfile=NONE tbinalg="LIN" tbinfile=NONE nxpix=40 nypix=40 binsz=0.25 coordsys="CEL" xref=20.396999 yref=26.040001 axisrot=0.0 rafield="RA" decfield="DEC" proj="AIT" hpx_ordering_scheme="RING" hpx_order=3 hpx_ebin=yes hpx_region="" evtable="EVENTS" sctable="SC_DATA" efield="ENERGY" tfield="TIME" chatter=3 clobber=yes debug=no gui=no mode="ql"
2020-05-14 10:19:50 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:19:50 INFO    GTBinnedAnalysis.run_gtapp(): WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
2020-05-14 10:19:50 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:19:50 INFO    GTBinnedAnalysis.run_gtapp(): This is gtbin version HEAD
2020-05-14 10:19:50 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtbin. Execution time: 0.81 s
2020-05-14 10:19:50 INFO    GTBinnedAnalysis.run_gtapp(): Running gtexpcube2.
2020-05-14 10:19:50 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtexpcube2 infile=/home/ubuntu/curve/J0121+2602/TBIN_115/data/ltcube_00.fits cmap=none outfile=/home/ubuntu/curve/J0121+2602/TBIN_115/data/bexpmap_00.fits irfs="P8R3_SOURCE_V2" evtype=3 nxpix=360 nypix=180 binsz=1.0 coordsys="CEL" xref=0.0 yref=0.0 axisrot=0.0 proj="CAR" ebinalg="LOG" emin=100.0 emax=300000.0 enumbins=14 ebinfile="NONE" hpx_ordering_scheme="RING" hpx_order=6 bincalc="EDGE" ignorephi=no thmax=180.0 thmin=0.0 table="EXPOSURE" chatter=3 clobber=yes debug=no mode="ql"
2020-05-14 10:20:05 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:20:05 INFO    GTBinnedAnalysis.run_gtapp(): WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
2020-05-14 10:20:05 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:20:05 INFO    GTBinnedAnalysis.run_gtapp(): This is gtexpcube2 version HEAD
2020-05-14 10:20:05 INFO    GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
2020-05-14 10:20:05 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R3_SOURCE_V2
2020-05-14 10:20:05 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  0  1
2020-05-14 10:20:05 INFO    GTBinnedAnalysis.run_gtapp(): Computing binned exposure map....................!
2020-05-14 10:20:05 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtexpcube2. Execution time: 1.26 s
WARNING: FITSFixedWarning: RADECSYS= 'FK5 '
the RADECSYS keyword is deprecated, use RADESYSa. [astropy.wcs.wcs]
2020-05-14 10:20:06 INFO    GTBinnedAnalysis.run_gtapp(): Running gtsrcmaps.
2020-05-14 10:20:06 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtsrcmaps scfile=/home/ubuntu/shifttransients/L20051316174620DF8BB210_SC00.fits sctable="SC_DATA" expcube=/home/ubuntu/curve/J0121+2602/TBIN_115/data/ltcube_00.fits cmap=/home/ubuntu/curve/J0121+2602/TBIN_115/data/ccube_00.fits srcmdl=/home/ubuntu/curve/J0121+2602/TBIN_115/data/srcmdl_00.xml bexpmap=/home/ubuntu/curve/J0121+2602/TBIN_115/data/bexpmap_00.fits wmap=none outfile=/home/ubuntu/curve/J0121+2602/TBIN_115/data/srcmap_00.fits irfs="P8R3_SOURCE_V2" evtype=3 convol=yes resample=yes rfactor=2 minbinsz=0.05 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=3 clobber=yes debug=no gui=no mode="ql"
2020-05-14 10:20:08 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:20:08 INFO    GTBinnedAnalysis.run_gtapp(): WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).
2020-05-14 10:20:08 INFO    GTBinnedAnalysis.run_gtapp():
2020-05-14 10:20:08 INFO    GTBinnedAnalysis.run_gtapp(): This is gtsrcmaps version HEAD
2020-05-14 10:20:08 INFO    GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
2020-05-14 10:20:08 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R3_SOURCE_V2
2020-05-14 10:20:08 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  0  1
2020-05-14 10:20:08 INFO    GTBinnedAnalysis.run_gtapp(): Floating point exception (core dumped)
2020-05-14 10:20:08 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 2.46 s
2020-05-14 10:20:08 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
2020-05-14 10:20:08 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
J0121+2602
isodiff
galdiff
Traceback (most recent call last):
  File "/home/ubuntu/runlc_monthly_shifted.py", line 58, in <module>
    main()
  File "/home/ubuntu/runlc_monthly_shifted.py", line 38, in main
    gta.setup()
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1068, in setup
    self._create_likelihood()
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1093, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 5349, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 71, in __init__
    pyLike.AppHelpers_checkExposureMap(srcMaps, binnedExpMap)
  File "/home/ubuntu/miniconda2/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 4899, in AppHelpers_checkExposureMap
    return _pyLikelihood.AppHelpers_checkExposureMap(cmapfile, emapfile)
RuntimeError: File not found: /home/ubuntu/curve/J0121+2602/TBIN_115/data/srcmap_00.fits

**Comment by eacharles** [comment]
Sorry from the slow reply.  The issue is that gtsrcmaps is crashing at the line: " 2020-05-14 10:20:08 INFO GTBinnedAnalysis.run_gtapp(): Floating point exception (core dumped)"

I'm not sure why gtsrcmaps is failing, it could be because of a problem with the configuration or because of an issue with the version of the fermitools you are running.    But in either case the problem lies outside of fermipy.
