### ISSUE TITLE
AttributeError: 'module' object has no attribute 'time'

### ISSUE THREAD

**Issue by imereu** [fermiPy/fermipy#361]
I have updated fermipy from 0.19 to 0.20 version but now I have a problem with one of my scipts. The results is this error message:
`Traceback (most recent call last):
  File "plotfitALL.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/Users/isabellamereu/.local/lib/python2.7/site-packages/matplotlib/__init__.py", line 118, in <module>
    import logging
  File "/Users/isabellamereu/opt/anaconda2/envs/fermi/lib/python2.7/logging/__init__.py", line 89, in <module>
    _startTime = time.time()
AttributeError: 'module' object has no attribute 'time'`

**Comment by imereu** [comment]
Solved
