### ISSUE TITLE
Fermipy 0.19.0 gtsrcmaps error

### ISSUE THREAD

**Issue by jleagle94** [fermiPy/fermipy#370]
Hi,

I am running Fermitools 1.2.23 and Fermipy 0.19.0 on a Docker container. I recently had to recreate the Docker container when I accidentally upgraded to Fermitools 2.0... And I keep getting this error that was not an issue before when loading source maps. It seems like Fermipy keeps re-generating source maps at each and every time the source maps are called - altering the file each time. 
```
(fermi) [fermi@1fc0339de6dc ~]$ conda list fermi
# packages in environment at /opt/anaconda/envs/fermi:
#
# Name                    Version                   Build  Channel
fermipy                   0.19.0                   pypi_0    pypi
fermitools                1.2.23           py27h39e3cac_0    fermi
fermitools-data           0.17                          0    fermi/label/beta

```
I am trying to load in an already done analysis using the GTAnalysis.create command and get the following error. This analysis is one that runs fine on a separate server but with my local machine using Docker, it's endlessly getting stuck on these source maps. Can someone help :( 
```
>>> gta = GTAnalysis.create('data_all_events/4fgl_bestfit.npy')
2020-10-12 16:14:52 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 0.19.0 
ScienceTools version unknown
2020-10-12 16:14:54 INFO    GTAnalysis.setup(): Running setup.
2020-10-12 16:14:54 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2020-10-12 16:14:54 INFO    GTBinnedAnalysis._select_data(): Skipping data selection.
2020-10-12 16:14:54 INFO    GTBinnedAnalysis._create_ltcube(): Skipping LT Cube.
2020-10-12 16:14:54 INFO    GTBinnedAnalysis._create_expcube(): Skipping gtexpcube.
2020-10-12 16:14:54 INFO    GTBinnedAnalysis._create_srcmaps(): Skipping gtsrcmaps.
2020-10-12 16:14:54 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
2020-10-12 16:14:54 INFO    GTBinnedAnalysis.setup(): Running setup for component 01
2020-10-12 16:14:54 INFO    GTBinnedAnalysis._select_data(): Skipping data selection.
2020-10-12 16:14:54 INFO    GTBinnedAnalysis._create_ltcube(): Skipping LT Cube.
2020-10-12 16:14:55 INFO    GTBinnedAnalysis._create_expcube(): Skipping gtexpcube.
2020-10-12 16:14:55 INFO    GTBinnedAnalysis._create_srcmaps(): Skipping gtsrcmaps.
2020-10-12 16:14:55 INFO    GTBinnedAnalysis.setup(): Finished setup for component 01
2020-10-12 16:14:55 INFO    GTBinnedAnalysis.setup(): Running setup for component 02
2020-10-12 16:14:55 INFO    GTBinnedAnalysis._select_data(): Skipping data selection.
2020-10-12 16:14:55 INFO    GTBinnedAnalysis._create_ltcube(): Skipping LT Cube.
2020-10-12 16:14:56 INFO    GTBinnedAnalysis._create_expcube(): Skipping gtexpcube.
2020-10-12 16:14:56 INFO    GTBinnedAnalysis._create_srcmaps(): Skipping gtsrcmaps.
2020-10-12 16:14:56 INFO    GTBinnedAnalysis.setup(): Finished setup for component 02
2020-10-12 16:14:56 INFO    GTBinnedAnalysis.setup(): Running setup for component 03
2020-10-12 16:14:56 INFO    GTBinnedAnalysis._select_data(): Skipping data selection.
2020-10-12 16:14:56 INFO    GTBinnedAnalysis._create_ltcube(): Skipping LT Cube.
2020-10-12 16:14:57 INFO    GTBinnedAnalysis._create_expcube(): Skipping gtexpcube.
2020-10-12 16:14:57 INFO    GTBinnedAnalysis._create_srcmaps(): Skipping gtsrcmaps.
2020-10-12 16:14:57 INFO    GTBinnedAnalysis.setup(): Finished setup for component 03
2020-10-12 16:14:57 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
2020-10-12 16:15:33 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 01.
2020-10-12 16:16:09 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 02.
2020-10-12 16:16:45 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 03.
2020-10-12 16:17:26 INFO    GTAnalysis.setup(): Finished setup.
2020-10-12 16:17:26 INFO    GTAnalysis.load_roi(): Loading ROI file: /data/pwn_igrj11014-6103/data_all_events/4fgl_bestfit.npy
2020-10-12 16:17:27 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 565, in create
    gta.load_roi(infile, params=params, mask=mask)
  File "/opt/anaconda/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 3615, in load_roi
    self._create_likelihood(infile)
  File "/opt/anaconda/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 1093, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/opt/anaconda/envs/fermi/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 5349, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/opt/anaconda/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 68, in __init__
    pyLike.AppHelpers_checkExposureMap(srcMaps, binnedExpMap)
  File "/opt/anaconda/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 5020, in AppHelpers_checkExposureMap
    return _pyLikelihood.AppHelpers_checkExposureMap(cmapfile, emapfile)
RuntimeError: File not in FITS or Root format: /data/pwn_igrj11014-6103/data_all_events/srcmap_00.fits
```

**Comment by jleagle94** [comment]
I believe this is a bug and a quick (albeit somewhat annoying) solution will be to move all PH event files (including the events.txt) to the output directory (the same directory that fermipy will write out the files into). Make sure to update the location of PH files and/or events.txt in the config file to point to the output directory.
