### ISSUE TITLE
TypeError in gta.write_roi with make_plots=True, fermipy 1.0.0

### ISSUE THREAD

**Issue by jeget** [fermiPy/fermipy#373]
I encountered an error in the same function call as in #371, namely when I call gta.write_roi('file', make_plots=True) I get

> Traceback (most recent call last):
  File "run1.py", line 20, in <module>
    gta.write_roi('issue', make_plots=True)
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 3755, in write_roi
    **kwargs.get('plotting', {}))
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 3830, in make_plots
    plotter.run(self, mcube_map, prefix=prefix, **kwargs)
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/fermipy/plotting.py", line 933, in run
    **kwargs)
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/fermipy/plotting.py", line 1219, in make_roi_plots
    rp.plot(cb_label='Counts', zscale='pow', gamma=1. / 3.)
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/fermipy/plotting.py", line 585, in plot
    im, ax = self._implot.plot(**im_kwargs)
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/fermipy/plotting.py", line 311, in plot
    im = ax.imshow(data, **kwargs_imshow)
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py", line 202, in imshow
    return super().imshow(X, *args, origin=origin, **kwargs)
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1438, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5523, in imshow
    im.set_data(X)
  File "/home/bulat/anaconda3/envs/fermipy3/lib/python3.7/site-packages/matplotlib/image.py", line 710, in set_data
    .format(self._A.shape))
TypeError: Invalid shape (1, 100, 100) for image data

In the traceback, there is a call to method `make_roi_plots()` which is defined in fermipy/plotting.py, line 1159. In that method, a `ROIPlotter` object is created, and in its contstructor the method `sum_over_axes()` is called which is from gammapy.maps.Map.
Now, in gammapy-0.18.2, this method is defined with
`def sum_over_axes(self, axes_names=None, keepdims=True, weights=None)`
while in gammapy-0.17 it reads
`def sum_over_axes(self, axes=None, keepdims=False)`.
As a result, when using gammapy-0.18.2, summed counts map has the shape `(1, nxpix, nypix)` instead of being squashed to `(nxpix, nypix)` which causes the error in `imshow()`.
So, in fermipy/plotting.py, line 393, I changed to `sum_over_axes(keepdims=False)` and the error disappeared. Probably, it should be changed in the package.

**Comment by eacharles** [comment]
Fixed with #380.
