### ISSUE TITLE
problem with MacOS and gta.optimize()

### ISSUE THREAD

**Issue by ChiRig** [fermiPy/fermipy#382]
Dear all,

I'm trying to perform an analysis with fermipy on my macOS Mojave 10.14.6 fermipy version 0.17.4, python 2.7
When I run optimize() I obtain this error:

RuntimeError: Failed to converge after 100 interations. 

>>> gta.optimize()
2021-02-11 15:15:18 INFO    GTAnalysis.optimize(): Starting
Joint fit  ['galdiff', 'isodiff', '4FGL J0505.3+0459', '4FGL J0532.6+0732', '4FGL J0509.4+0542']
/Users/muse/miniconda/envs/fermipy/lib/python2.7/site-packages/fermipy/utils.py:785: RuntimeWarning: invalid value encountered in less
  if np.any(fn_val[imax:] < -dlnl_limit):
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/muse/miniconda/envs/fermipy/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 2294, in optimize
    self.fit(loglevel=logging.DEBUG, **config['optimizer'])
  File "/Users/muse/miniconda/envs/fermipy/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 3010, in fit
    self.update_source(name, reoptimize=config['reoptimize'])
  File "/Users/muse/miniconda/envs/fermipy/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 3988, in update_source
    optimizer=optimizer)
  File "/Users/muse/miniconda/envs/fermipy/lib/python2.7/site-packages/fermipy/gtanalysis.py", line 4157, in get_src_model
    lnlp['flux'], lnlp['dloglike'])
  File "/Users/muse/miniconda/envs/fermipy/lib/python2.7/site-packages/fermipy/utils.py", line 803, in get_parameter_limits
    ul = find_function_root(fn, x0, xhi, dlnl_limit, bounds=bounds)
  File "/Users/muse/miniconda/envs/fermipy/lib/python2.7/site-packages/fermipy/utils.py", line 677, in find_function_root
    return brentq(lambda t: fn(t) + delta, x0, xb, xtol=xtol)
  File "/Users/muse/miniconda/envs/fermipy/lib/python2.7/site-packages/scipy/optimize/zeros.py", line 442, in brentq
    r = _zeros._brentq(f,a,b,xtol,rtol,maxiter,args,full_output,disp)
RuntimeError: Failed to converge after 100 iterations.

I already tried to update the version of fermipy, but in that case I obtain another problem on the lightcurve analysis. This is the reason why I would like to use this version of fermipy.
Thanks!

**Comment by henrikef** [comment]
@ChiRig Can you try upgrading to `fermipy 1.1.4` and `fermitools 2.2.0`? See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. The lightcurve bug is fixed in the new version. Please let me know if your convergence issue persists.

**Comment by henrikef** [comment]
Please re-open if this is still a problem in `fermitools 2.2.0` and `fermipy 1.1.5` or later.
