### ISSUE TITLE
TypeError: to_hdulist() got an unexpected keyword argument 'format' - fermipy 1.0.1

### ISSUE THREAD

**Issue by ldivenere** [fermiPy/fermipy#398]
I have this error during setup, after the creation of gtsrcmaps:

```
2021-04-01 20:40:00 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
2021-04-01 20:40:00 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
2021-04-01 20:40:00 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Creating BinnedObs
2021-04-01 20:40:00 DEBUG   GTBinnedAnalysis._create_binned_analysis(): {'srcMaps': '/lustrehome/divenere/Fermi/fermipy_output_year2020_delta1_step0/srcmap_00.fits', 'expCube': '/lustrehome/divenere/Fermi/fermipy_output_year2020_delta1_step0/ltcube_00.fits', 'binnedExpMap': '/lustrehome/divenere/Fermi/fermipy_output_year2020_delta1_step0/bexpmap_00.fits', 'irfs': 'P8R3_SOURCE_V3'}
2021-04-01 20:40:04 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis
2021-04-01 20:40:04 DEBUG   GTBinnedAnalysis._create_binned_analysis(): {'srcModel': '/lustrehome/divenere/Fermi/fermipy_output_year2020_delta1_step0/srcmdl_00.xml', 'optimizer': 'MINUIT', 'wmap': None, 'convolve': True, 'resample': True, 'minbinsz': 0.05, 'resamp_fact': 2, 'edisp_bins': -2}
Drm_Cache::update Measured counts < 0 4FGL J0003.6+3059 35 -5.70268e-23 3.21146e-24
1.77918e-06 7.00294e-06 2.29762e-05 6.01824e-05 0.000129674 0.000230231 0.000344153 0.000434293 0.000455892 0.000412345 0.000318215 0.000208918 0.000120906 5.96517e-05 2.6853e-05 1.03671e-05 3.7777e-06 1.19691e-06 3.47067e-07 8.7063e-08 2.11446e-08 4.51043e-09 8.69355e-10 1.4639e-10 2.22499e-11 2.93913e-12 3.45359e-13 3.5466e-14 3.24173e-15 2.58847e-16 1.81916e-17 1.1064e-18 5.82991e-20 2.60353e-21 1.00293e-22 3.21146e-24
2021-04-01 20:40:47 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Disabling energy dispersion for isodiff
2021-04-01 20:40:47 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Computing fixed weights
2021-04-01 20:40:58 DEBUG   GTBinnedAnalysis._create_binned_analysis(): Updating source maps
Traceback (most recent call last):
  File "fermipy_analysis.py", line 79, in <module>
    gta = GTAnalysis(config_file, fileio={"outdir":outdir, "logfile":outdir+"/logfile.log"}, selection={"tmin":tmin, "tmax":tmax, "ra":ra, "dec":dec, "emin":emin, "emax":emax, "zmax":zmax, "filter":filter_expr}, logging={'verbosity' : 4})
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 1085, in setup
    self._create_likelihood()
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 1117, in _create_likelihood
    self._init_roi_model()
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 1152, in _init_roi_model
    self._coadd_maps(cmaps, shape, rm, wmaps)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 4018, in _coadd_maps
    self._ccube.write(self.files['ccube'], overwrite=True, format='fgst-ccube')
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/gammapy/maps/base.py", line 328, in write
    hdulist = self.to_hdulist(**kwargs)
TypeError: to_hdulist() got an unexpected keyword argument 'format'
 
```
I'm using fermipy version 1.0.1, gammapy version 0.17 and astropy version 3.2.3.

**Comment by ldivenere** [comment]
Since the error seems to be related to gammapy, I tried updating gammapy to 0.18.2 using pip:
```
pip install gammapy --upgrade
```
This required also an automatic update of astropy to version 4.2.1. However this error appeared at the end of the process:
```
fermipy 1.0.1 requires astropy<4, but you'll have astropy 4.2.1 which is incompatible.
 ```


I then ran again the command:
```
pip install fermipy --upgrade
```
This operation downgraded astropy to version 3.2.3, leaving gammapy to version 0.18.2, and of course showing the error:
 ```
gammapy 0.18.2 requires astropy>=4.0, but you'll have astropy 3.2.3 which is incompatible.
 ```

This configuration (i.e. fermipy 1.0.1, gammapy 0.18.2, astropy 3.2.3) seems to solve the previous issue. I can successfully run a fermipy script with ROI loading, add/delete source operations, fitting, ts map/residmap and SED calculation.

However, there could be other parts of the code which could be broken due to the incompatible astropy version.
Any suggestions on which are the "correct" versions to use for the three packages and how to properly install them inside my conda environment?

**Comment by ldivenere** [comment]
For completeness, I also tried running the same script with fermipy 1.0.1, gammapy 0.18.2 and astropy 4.2.1.
However, I get this error in the write_roi() method:
```
2021-04-02 00:45:23 INFO    GTBinnedAnalysis.write_xml(): Writing /lustrehome/divenere/Fermi/fermipy_output_year2020_delta1_step0_fermitools2.0.0//out_optim_00.xml...
2021-04-02 00:45:23 INFO    GTAnalysis.write_fits(): Writing /lustrehome/divenere/Fermi/fermipy_output_year2020_delta1_step0_fermitools2.0.0//out_optim.fits...
Traceback (most recent call last):
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/astropy/table/table.py", line 2827, in insert_row
    newcol = col.insert(index, val, axis=0)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/astropy/table/column.py", line 1206, in insert
    self_for_insert = _expand_string_array_for_values(self, values)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/astropy/table/column.py", line 147, in _expand_string_array_for_values
    values_str_len = np.char.str_len(values).max()
  File "<__array_function__ internals>", line 6, in str_len
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/numpy/core/defchararray.py", line 283, in str_len
    return _vec_string(a, int_, '__len__')
TypeError: string operation on non-string array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fermipy_analysis.py", line 83, in <module>
    gta.write_roi(outname)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 3722, in write_roi
    self.write_fits(fitsfile)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 3760, in write_fits
    tab = self.roi.create_table()
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/fermipy/roi_model.py", line 2224, in create_table
    s.add_to_table(tab)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/fermipy/roi_model.py", line 522, in add_to_table
    tab.add_row(row)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/astropy/table/table.py", line 2719, in add_row
    self.insert_row(len(self), vals, mask)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_0/lib/python3.7/site-packages/astropy/table/table.py", line 2851, in insert_row
    .format(name, err))
ValueError: Unable to insert row because of exception in column 'Spatial_Filename':
string operation on non-string array

```

**Comment by eacharles** [comment]
All of these errors are coming because gammapy changed their interfaces.   

The easiest is probably to install the newest version of fermipy in a clean environment.

**Comment by ldivenere** [comment]
I created a clean environment with fermitools 2.0.8 (latest version available). Then, in this environment I installed fermipy:
```
conda install -c conda-forge -c fermi fermipy
```
I now have:
```
>>> gammapy.__version__
'0.18.2'
>>> fermipy.__version__
'v1.0.1'
>>> astropy.__version__
'3.2.3'
```
With a fresh installation I had a matplotlib issue, which I solved by downgrading matplotlib from version 3.4.1 to 3.3.2. 
I've reported the error here: #399 

Regarding the astropy issue, conda did not complain about the 'old' astropy version during the installation, while I previously had the error message when using pip. 
Digging a bit into gammapy code, I found out that the setup.cfg file in gammapy explicitly requires astropy>4, while the conda yml environment does not have any constraint on astropy version. This is of course a gammapy-related issue, and hopefully it doesn't affect fermipy.

**Comment by ldivenere** [comment]
The incompatibility of astropy versions was already known and a fix was already implemented here:
https://github.com/fermiPy/fermipy/pull/380#issuecomment-776369155

**Comment by henrikef** [comment]
This should be fixed in `fermipy 1.1.4` and `fermitools 2.2.0` 🤞. See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. I am going to close this issue. Please re-open if you still get the same error after a fresh install of the new versions.
