### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (0,) (0,10) - fermipy version v1.0.1, ScienceTools version 2.0.8

### ISSUE THREAD

**Issue by sdegaetano93** [fermiPy/fermipy#404]
I created a configuration file with a pointlike source (simply named PointSource) and I performed the following three steps in my python script:

# simulating ROI with only PointSource
galdiff = gta.delete_source('galdiff')
gta.delete_sources(exclude="PointSource")
gta.simulate_roi()
gta.fit()
gta.print_roi()
gta.write_roi('fit_pointsource',make_plots=True)

# simulating ROI with PointSource and galactic diffuse
gta.add_source('galdiff',galdiff)
gta.simulate_roi()
gta.fit()
gta.print_roi()
gta.write_roi('fit_pointsource_galdiff',make_plots=True)

# simulating ROI with only galactic diffuse
gta.delete_source('PointSource')
gta.simulate_roi()
gta.fit()
gta.print_roi()
gta.write_roi('fit_galdiff',make_plots=True)

The first two steps are performed with no issues, while in the last one I get the following lines:

Traceback (most recent call last):
  File "run_sources.py", line 33, in <module>
    gta.write_roi('fit_galdiff',make_plots=True)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_8/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 3722, in write_roi
    self.write_fits(fitsfile)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_8/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 3793, in write_fits
    fits_utils.write_hdus(hdus, fitsfile)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_8/lib/python3.7/site-packages/fermipy/fits_utils.py", line 112, in write_hdus
    hdulist.writeto(outfile, overwrite=True)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_8/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_8/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 928, in writeto
    hdu._prewriteto(checksum=checksum)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_8/lib/python3.7/site-packages/astropy/io/fits/hdu/table.py", line 502, in _prewriteto
    update_heap_pointers=not self._manages_own_heap)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_8/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py", line 1136, in _scale_back
    self._scale_back_strings(indx, dummy, raw_field)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_8/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py", line 1183, in _scale_back_strings
    _ascii_encode(input_field, out=output_field)
  File "/lustrehome/exp_soft/glast_local/anaconda3/envs/FT_2_0_8/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py", line 1321, in _ascii_encode
    op_flags=op_flags, flags=['zerosize_ok'])
ValueError: operands could not be broadcast together with shapes (0,) (0,10)

In particular, the fits file related to this step is empty and consequently no npy file is created.
It seems that this error appears when the model includes only diffuse sources, while it disappears if at least a point source is added to the model.

**Comment by henrikef** [comment]
This should be fixed in `fermipy 1.1.4` and `fermitools 2.2.0`. See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. I am going to close this issue. Please re-open if you still get the same error after a fresh install of the new versions.
