### ISSUE TITLE
conda Installation instructions in docs are wrong

### ISSUE THREAD

**Issue by maxnoe** [fermiPy/fermipy#416]
The conda install instructions give here are invalid: https://fermipy.readthedocs.io/en/latest/install.html

```
$ conda env create --name fermipy -c conda-forge -c fermipy python=3.7 fermitools=2.0.8
usage: conda-env [-h] {create,export,list,remove,update,config} ...
conda-env: error: unrecognized arguments: -c -c fermipy python=3.7 fermitools=2.0.8
```

To create an environment on the command-line giving packages, it needs to be without the `env`:

```
conda create --name fermipy -c conda-forge -c fermipy python=3.7 fermitools=2.0.8
```

However, also then, I just get:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - fermitools=2.0.8

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/fermipy/linux-64
  - https://conda.anaconda.org/fermipy/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Same with mamba.

Looking around, I found that this works to get the packages installed:

```
mamba create --name fermipy -c conda-forge -c fermi -c fermipy python=3.7 fermitools=2.0.8 fermipy
```

But then importing stuff from fermipy fails searching for a shared library:

```
❯ python -c 'from fermipy.gtanalysis import GTAnalysis'
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/maxnoe/.local/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 21, in <module>
    import fermipy.gtutils as gtutils
  File "/home/maxnoe/.local/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtutils.py", line 6, in <module>
    import pyLikelihood as pyLike
  File "/home/maxnoe/.local/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermitools/pyLikelihood.py", line 15, in <module>
    import _pyLikelihood
ImportError: libCLHEP-2.4.4.1.so: cannot open shared object file: No such file or directory```
```

The version that is installed is `2.4.4.2`:

```
❯ find ~/.local/anaconda3/envs/fermipy/lib -name 'libCLHEP*.so'
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-Evaluator-2.4.4.2.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-Vector-2.4.4.2.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-Random-2.4.4.2.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-GenericFunctions-2.4.4.2.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-RefCount-2.4.4.2.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-Geometry-2.4.4.2.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-Exceptions-2.4.4.2.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-Matrix-2.4.4.2.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-2.4.4.2.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-RandomObjects-2.4.4.2.so
/home/maxnoe/.local/anaconda3/envs/fermipy/lib/libCLHEP-Cast-2.4.4.2.so
```

**Comment by sushmitaagarwal** [comment]
I encountered a similar problem.
Look up a similar issue : https://github.com/fermi-lat/Fermitools-conda/issues/101
Also check this answer for installation: #414

**Comment by relleums** [comment]
Exact same problem here.

**Comment by LeandroMatheumatical** [comment]
The same problem here

**Comment by henrikef** [comment]
Currently, you need to specify the version of CLHEP that works with the fermi tools, see here: https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions  

Try

```
conda create -n fermi -c conda-forge -c fermipy -c fermi python=3.7 fermitools=2.0.8 fermipy clhep=2.4.4.1
```

to install the fermi tools and fermipy at the same time.

**Comment by LeandroMatheumatical** [comment]
> Currently, you need to specify the version of CLHEP that works with the fermi tools, see here: https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions
> 
> Try
> 
> ```
> conda create -n fermi -c conda-forge -c fermipy -c fermi python=3.7 fermitools=2.0.8 fermipy clhep=2.4.4.1
> ```
> 
> to install the fermi tools and fermipy at the same time.

Thank you henrikef, its solved my problem.

**Comment by henrikef** [comment]
Fixed on the webpage too.
