### ISSUE TITLE
Make python setup.py test work with Python 3

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#42]
For easier Fermipy / Gammapy collaboration it would be nice to have `python setup.py install` and `python setup.py test` for Fermipy work with Python 3 and without the science tools (i.e. make those an optional dependency as far as install is concerned).

This is very easy to achieve ... following #41 it's just minor changes like this one that are needed:
```
$ python setup.py test
No module named 'version'
running test
running egg_info
writing fermipy.egg-info/PKG-INFO
writing requirements to fermipy.egg-info/requires.txt
writing entry points to fermipy.egg-info/entry_points.txt
writing top-level names to fermipy.egg-info/top_level.txt
writing dependency_links to fermipy.egg-info/dependency_links.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'fermipy.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    'wcsaxes'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/command/test.py", line 180, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/deil/code/fermipy/fermipy/castro.py", line 31, in <module>
    import fermipy.utils as utils
  File "/Users/deil/code/fermipy/fermipy/utils.py", line 496
    def parabola((x, y), amplitude, x0, y0, sx, sy, theta):
                 ^
SyntaxError: invalid syntax
```

@woodmd - If you merge  #41 I can make a pull request with a small diff suggesting fixes for this and a few other minor issues.

**Comment by woodmd** [comment]
#41 is now merged so feel free to go ahead with the other PR.

**Comment by cdeil** [comment]
Note to sef: with #41 and #45 I can run `python setup.py test` and all I get is import errors if I don't have the science tools.

The next step would be to declare which tests depend on the ST using something like this:
http://docs.gammapy.org/en/latest/api/gammapy.utils.testing.requires_dependency.html

Given that we're starting to move non-ST specific code over to Gammapy, maybe that's not useful?

For me it would be OK to use the ST Python to continue working on Fermipy code, so @woodmd, if you don't think it's useful to add the `requires_dependency('ST')` decorators to Fermipy tests, we should close this issue.

**Comment by woodmd** [comment]
I like the idea of having some parts of fermipy that could be tested without a ST installation so implementing the dependency decorators looks like a good approach for that.

Quite a few of the modules don't depend on the STs (e.g. `utils`, `castro`).  With some additional work I could probably strip out the ST dependencies from `roi_model`.

**Comment by cdeil** [comment]
https://travis-ci.org/fermiPy/fermipy/jobs/146364911
Closing this issue.
