### ISSUE TITLE
RuntimeError: Cannot read keyword "NDSKEYS" in file [srcmap_00.fits] (CFITSIO ERROR 202: keyword not found in header)

### ISSUE THREAD

**Issue by qsebas21** [fermiPy/fermipy#425]
Hello,

I'm using fermipy version v1.0.1, ScienceTools version 2.0.8. I get an error when performing an analysis of a region, and I'm getting a traceback which says the following:

Traceback (most recent call last):
  File "analisisMorf.py", line 4, in <module>
    gta.setup()
  File "/home/sebastian/miniconda3/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 1085, in setup
    self._create_likelihood()
  File "/home/sebastian/miniconda3/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 1112, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/home/sebastian/miniconda3/envs/fermi/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 5402, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/home/sebastian/miniconda3/envs/fermi/lib/python3.7/site-packages/fermitools/BinnedAnalysis.py", line 71, in __init__
    self._createObservation(srcMaps, expCube, self.irfs)
  File "/home/sebastian/miniconda3/envs/fermi/lib/python3.7/site-packages/fermitools/BinnedAnalysis.py", line 74, in _createObservation
    self._respFuncs.load_with_event_types(irfs, "", self.srcMaps, "")
  File "/home/sebastian/miniconda3/envs/fermi/lib/python3.7/site-packages/fermitools/pyLikelihood.py", line 6594, in load_with_event_types
    return _pyLikelihood.ResponseFunctions_load_with_event_types(self, respFuncs, respBase, filename, extname)
RuntimeError: Cannot read keyword "NDSKEYS" in file "/home/sebastian/Documentos/Lab/srcmap_00.fits" (CFITSIO ERROR 202: keyword not found in header)

[Here](https://github.com/fermiPy/fermipy/files/7026293/resultados1.txt) is the full terminal output. It appears the error could also be near the end, with the line:
GTBinnedAnalysis.run_gtapp(): Generating SourceMap for galdiff 21Killed.

Any help is much appreciated. Thanks!

**Comment by GajVan** [comment]
Hi,
  most probably this kind of error arises due to mismatch of energy range selected by user during the analysis. May be some of the data lies outside the energy range.

**Comment by henrikef** [comment]
@qsebas21 Does this issue persist with `fermipy 1.1.4` and `fermitools 2.2.0`? See [here](https://fermipy.readthedocs.io/en/latest/install.html) for installation instructions. Please make sure to delete and recreate all intermediate data files such as the `srcmap_00.fits` etc. Please let me know if still get the same error after a fresh install of the new versions.

**Comment by henrikef** [comment]
Please re-open if this is still a problem in `fermitools 2.2.0` and `fermipy 1.1.5` or later.

**Comment by GajVan** [comment]
Thanks Fermipy/Fermipy
  I will check , if it is still showing, I will share with you.
Thank you
*Gajanan D. Harale*
*Assistant Professor*
*Dept. Of Physics*
*Fergusson College Pune*
*Pune-4*

**Comment by TheCriticalSpan** [comment]
Did this issue ever get fixed? I'm having the same problem with my code right now. Checked my config file already and everything seems to be in order.

**Comment by WolfgangSuperman** [comment]
We're still having this problem. Is it resolved with the new 1.3.1 version?
