### ISSUE TITLE
TypeError:register_cmap() got an unexpected keyword argument 'data'

### ISSUE THREAD

**Issue by Shruti0342** [fermiPy/fermipy#439]
I am using fermipy to analyse data, when I am trying to plot residual map I am getting this output.

>>> maps = gta.residmap('fit_model',model=model, make_plots=True)
2022-02-04 20:06:42 INFO    GTAnalysis.residmap(): Generating residual maps
2022-02-04 20:06:42 INFO    GTAnalysis.add_source(): Adding source residmap_testsource
2022-02-04 20:06:44 INFO    GTAnalysis.delete_source(): Deleting source residmap_testsource
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/residmap.py", line 265, in residmap
    plotter.make_residmap_plots(o, self.roi)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/plotting.py", line 982, in make_residmap_plots
    load_bluered_cmap()
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/plotting.py", line 164, in load_bluered_cmap
    plt.register_cmap(name='bluered', data=bluered)
TypeError: register_cmap() got an unexpected keyword argument 'data'

**Comment by henrikef** [comment]
Could you let me know what versions of fermipy and matplotlib you are using?

**Comment by Shruti0342** [comment]
I have fermipy v1.0.1 and matplotlib 3.3.2

**Comment by henrikef** [comment]
Can you try downgrading to matplotlib 3.2.1? Or install a fresh environment with the packages listed in #437 ?

**Comment by Shruti0342** [comment]
i have installed a fresh environment, but did not try this version of matplotlib 3.2.1, now i am trying.

**Comment by Shruti0342** [comment]
hii @henrikef, i just want to know, should i have many other versions of matplotlib or i should have only one version ?

**Comment by henrikef** [comment]
I think in a given environment you should only have one version.

I'm not sure that 3.2.1 is the best but it was what I had installed in an
older environment that seemed to work. I know there are some
incompatibilities with newer versions of matplotlib. They have mostly been
fixed on the master branch, but that one has other dependency issues :/

**Comment by Shruti0342** [comment]
okay, but again same problem arises. Now what should I do ?

**Comment by Shruti0342** [comment]
Yes, it is running now, with matplotlib 3.2.1
Thank you so much !@henrikef
