### ISSUE TITLE
KeyError: 'fit_success' when running the code lc = gta.lightcurve

### ISSUE THREAD

**Issue by Shruti0342** [fermiPy/fermipy#446]
I am using fermipy v1.0.1, numpy 1.16.1, matplotlib 3.2.1
when i am running the code 
lc = gta.lightcurve('mkn421', binsz=86400.*7.0, free_radius=3.0, use_scaled_srcmap=True)
then i am getting this output
>>> lc = gta.lightcurve('mkn421', binsz=86400.*7.0, free_radius=3.0, use_scaled_srcmap=True)
2022-03-11 14:19:50 INFO    GTAnalysis.lightcurve(): Computing Lightcurve for 4FGL J1104.4+3812
2022-03-11 14:19:52 INFO    lightcurve_239557414_240162214 GTAnalysis._process_lc_bin(): Fitting time range 239557414 240162214
2022-03-11 14:19:53 INFO    lightcurve_239557414_240162214 GTBinnedAnalysis._create_ltcube(): Generating local LT cube.
Analysis failed in time range 239557414 240162214
<class 'AttributeError'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py", line 289, in lightcurve
    o = self._make_lc(name, **config)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py", line 452, in _make_lc
    if not next_fit['fit_success']:
KeyError: 'fit_success'

 so is there needed to change any of these version that i have written above !

**Comment by henrikef** [comment]
Hi @Shruti0342  ! This should (I hope) be fixed now in the pre-release version (still being tested). If you want, you could test the development version of the fermitools and corresponding version of fermipy:

```
mamba create -n fermi-21 -c fermi -c conda-forge -c fermi/label/dev "fermitools>=2.1.0"
mamba activate fermi-21
pip install git+https://github.com/fermiPy/fermipy.git@v1.1.1
```

(I recommend using `mamba` instead of `conda`, it has a similar UI but resolves requirements much faster. You can try `conda` instead).

Please let me know if that helps.
