### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (0,) (0,10) when i am running gta.lightcurve

### ISSUE THREAD

**Issue by Shruti0342** [fermiPy/fermipy#447]
i use fermipy v1.0.1, numpy v1.16.1, matplotlib v3.2.1, astropy v3.2.3
when i an running the code 
lc = gta.lightcurve() i am getting this output
>>> lc = gta.lightcurve('sourceA', binsz=86400.*100.0, free_radius=3.0)
2022-03-11 19:53:52 INFO    GTAnalysis.lightcurve(): Computing Lightcurve for 4FGL J1048.4+7143
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py", line 297, in lightcurve
    self._make_lc_fits(o, filename + '.fits', **config)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py", line 332, in _make_lc_fits
    fits_utils.write_hdus(hdus, filename, keywords=keywords)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/fits_utils.py", line 112, in write_hdus
    hdulist.writeto(outfile, overwrite=True)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 928, in writeto
    hdu._prewriteto(checksum=checksum)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/astropy/io/fits/hdu/table.py", line 502, in _prewriteto
    update_heap_pointers=not self._manages_own_heap)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py", line 1136, in _scale_back
    self._scale_back_strings(indx, dummy, raw_field)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py", line 1183, in _scale_back_strings
    _ascii_encode(input_field, out=output_field)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/astropy/io/fits/fitsrec.py", line 1321, in _ascii_encode
    op_flags=op_flags, flags=['zerosize_ok'])
ValueError: operands could not be broadcast together with shapes (0,) (0,10) 

please help me, what i need to change in this coding or any of the versions that i have mentioned at the top ?

**Comment by spletts** [comment]
I am also getting this error while using: astropy 3.2.3, the following branch of fermipy: [https://github.com/ldivenere/fermipy/tree/431-plsec4](https://github.com/ldivenere/fermipy/tree/431-plsec4) & Fermitools 2.0.8, numpy 1.20.2, and matplotlib 3.2.1

**Comment by henrikef** [comment]
Hi @spletts ! This should (I hope) be fixed now in the pre-release version (still being tested). If you want, you could test the development version of the fermitools and corresponding version of fermipy:

```
mamba create -n fermi-21 -c fermi -c conda-forge -c fermi/label/dev "fermitools>=2.1.0"
mamba activate fermi-21
pip install git+https://github.com/fermiPy/fermipy.git@v1.1.1
```

(I recommend using `mamba` instead of `conda`, it has a similar UI but resolves requirements much faster. You can try `conda` instead).

Please let me know if that helps.

**Comment by spletts** [comment]
Hi @henrikef ! I was getting this error because I set `binsz` too small, so this issue is resolved for me (without testing the pre-release). Thanks for following up!
