### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sunanda15** [fermiPy/fermipy#494]
I am doing the lightcurve analysis for TXS 0506+056 source. After the step, gta = GTAnalysis('config1.yaml',logging={'verbosity' : 3}) .  I am getting error in gta.setup()
I have copied the error below, Please guide me on how I can resolve this issue
cienceTools version 2.0.8
2022-08-03 12:00:00 INFO    GTAnalysis.setup(): Running setup.
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtselect infile=/home/sunanda/mkn421/lightcurve1/evfile_00.txt outfile=/home/sunanda/mkn421/lightcurve1/ft1_00.fits ra=77.35929870605469 dec=5.701399803161621 rad=1.2071067811865475 tmin=520560005.0 tmax=567993605.0 emin=500.0 emax=100000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): This is gtselect version HEAD
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Fatal in <TROOT::InitInterpreter>: cannot load library /home/sunanda/root/root-6.20.04-install/lib/libRIO.so: undefined symbol: _ZN6TClass8GetClassERKSt9type_infobb
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtselect. Execution time: 0.09 s
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Running gtltcube.
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtltcube evfile="/home/sunanda/mkn421/lightcurve1/ft1_00.fits" evtable="EVENTS" scfile=L220803020958D7616F2375_SC00.fits sctable="SC_DATA" outfile=/home/sunanda/mkn421/lightcurve1/ltcube_00.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=90.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Caught St13runtime_error at the top level: File not found: /home/sunanda/mkn421/lightcurve1/ft1_00.fits
2022-08-03 12:00:00 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 0.11 s
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    gta.setup()
  File "/home/sunanda/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 1082, in setup
    c.setup(overwrite=overwrite)
  File "/home/sunanda/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 5121, in setup
    self._ltc = LTCube.create(self.files['ltcube'])
  File "/home/sunanda/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/ltcube.py", line 192, in create
    ltc = cls.create_from_fits(files[0])
IndexError: list index out of range

**Comment by henrikef** [comment]
@sunanda15 see this error:

```
Fatal in TROOT::InitInterpreter: cannot load library /home/sunanda/root/root-6.20.04-install/lib/libRIO.so: undefined symbol
```

It indicates an issue with your underlying fermitools install. Please contact the fermitools helpdesk or upgrade to fermitools 2.2.1 ([see installation instructions](https://fermipy.readthedocs.io/en/latest/install.html)).
