### ISSUE TITLE
While running gta.setup(), gtltcube is generating an error 

### ISSUE THREAD

**Issue by Sushanth99** [fermiPy/fermipy#497]
While running `gta.setup()`, the code is crashing with the following error: `IndexError: list index out of range`. The data is dowloaded directly from [Fermi-LAT website](https://fermi.gsfc.nasa.gov/cgi-bin/ssc/LAT/LATDataQuery.cgi).

**To Reproduce**
First ran `gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})` and then `gta.setup()`. No `ltcube` file was provided in the `config.yaml` file.

**Log files**
The following message appeared in the log files while running the code was executing `gtltcube`:
`
GTBinnedAnalysis.run_gtapp(): Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtltcube; Ape exception code 19 (at /Users/runner/miniforge3/conda-bld/fermitools_1655479516925/work/src/hoops/src/hoops_ape.cxx: 435)
`

**Environment:**
 - OS: (e.g. MacOS Monterey version 12.5.1)
 - `Darwin xxxxxxs-MacBook-Air.local 21.6.0 Darwin Kernel Version 21.6.0
 - fermipy 1.1.6, fermitools 2.2.0, and fermitools-data 0.18

**Comment by henrikef** [comment]
Hi @Sushanth99!

To me, this looks like an issue with the fermi tools, not fermipy.

Can you run `gtltcube` on its own (on the command line)? What happens if you run other fermitools apps such as `gtirfs` (should print out IRF files) or `test_Likelihood` on the command line?

**Comment by Sushanth99** [comment]
Hi @henrikef,

I ran `gtltcube` from the command line using the same command present in the logs of `gta.setup()` before crashing. It seems to be working fine. Also, `gtirfs` too is printing out the IRF files. 

I also tried linking the `ltcube.fits` file generated from running `gtltcube` from the command line to the `config.yaml` file. In this case, the `gta.setup()` is still crashing while running `gtbin` with the same error. 

**NOTE**: I am running this analysis from an external hard disk. All the data files and jupyter notebook are stored in that disk.

**Comment by henrikef** [comment]
@Sushanth99 are you still experiencing this issue? If so, please try updating to fermitools 2.2.0 and fermipy 1.2 (on pip). Please also try restarting the analysis in a fresh, empty directory. If that does not help, please send us the full output and the list of commands you are using.

**Comment by basuparth** [comment]
Hi, @henrikef I am facing the same issue while analyzing a GRB. I am attaching my analysis files below. I have mostly analyzed bazars using fermipy before but never run into these errors before. My actual files have the extension .yaml, .list and .py of course. By the way why doesn't fermipy accept the name GRB 221009A in the "field" target when I use the  same name to download the data from fermi LAT.

  
[config.txt](https://github.com/fermiPy/fermipy/files/11645827/config.txt)
[events.txt](https://github.com/fermiPy/fermipy/files/11645828/events.txt)
[fermipy_analyser.txt](https://github.com/fermiPy/fermipy/files/11645829/fermipy_analyser.txt)

**Comment by Sushanth99** [comment]
Hi, the error is still there on fermipy 1.2. I am running the analysis on SciServer. I am attaching the standard error file. 
[stderr_fermipy.txt](https://github.com/fermiPy/fermipy/files/12504505/stderr_fermipy.txt)

**Comment by NithyaSathyan** [comment]
Hii..
I have the same issue. My log file is as follows : 
2023-12-30 22:10:51 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 1.2.0 
ScienceTools version 2.2.0
2023-12-30 22:10:52 INFO    GTAnalysis.setup(): Running setup.
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtselect infile=/home/dell/data backup ubuntu dell mint/Documents/low_z_BLLACs/1H1914-194/evfile_00.txt outfile=/home/dell/data backup ubuntu dell mint/Documents/low_z_BLLACs/1H1914-194/ft1_00.fits ra=289.4383850097656 dec=-19.36280059814453 rad=7.5710678118654755 tmin=239557417.0 tmax=686188805.0 emin=1000.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): Parameter "infile" duplicated on command line.
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): Parameter "infile" duplicated on command line.
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtselect; Ape exception code 19 (at /home/conda/feedstock_root/build_artifacts/fermitools_1655479216784/work/src/hoops/src/hoops_ape.cxx: 435)
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtselect. Execution time: 0.12 s
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): Running gtltcube.
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtltcube evfile="/home/dell/data backup ubuntu dell mint/Documents/low_z_BLLACs/1H1914-194/ft1_00.fits" evtable="EVENTS" scfile=L2312300759163550A79855_SC00.fits sctable="SC_DATA" outfile=/home/dell/data backup ubuntu dell mint/Documents/low_z_BLLACs/1H1914-194/ltcube_00.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=90.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): Parameter "evfile" duplicated on command line.
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): Parameter "evfile" duplicated on command line.
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtltcube; Ape exception code 19 (at /home/conda/feedstock_root/build_artifacts/fermitools_1655479216784/work/src/hoops/src/hoops_ape.cxx: 435)
2023-12-30 22:10:52 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 0.12 s
Traceback (most recent call last):
  File "/home/dell/data backup ubuntu dell mint/Documents/low_z_BLLACs/1H1914-194/xx.py", line 4, in <module>
    gta.setup()
  File "/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1087, in setup
    c.setup(overwrite=overwrite)
  File "/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5176, in setup
    self._ltc = LTCube.create(self.files['ltcube'])
  File "/home/dell/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/ltcube.py", line 192, in create
    ltc = cls.create_from_fits(files[0])
IndexError: list index out of range

**Comment by omodei** [comment]
The problem is due to the path of your files that include spaces: "data backup ubuntu dell". The way fermitools are called is not compatible with this type if syntax. Try to move all your files in a different directory without spaces in its name.
