### ISSUE TITLE
Lightcurve creation failure [keyError: 'fit_success']

### ISSUE THREAD

**Issue by Shruti0342** [fermiPy/fermipy#499]
when i am trying to generate the lightcurve i am getting this error

Analysis failed in time range 445305603 445327203
<class 'OSError'>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py", line 289, in lightcurve
    o = self._make_lc(name, **config)
  File "/home/shruti/anaconda3/envs/fermi/lib/python3.7/site-packages/fermipy/lightcurve.py", line 452, in _make_lc
    if not next_fit['fit_success']:
KeyError: 'fit_success'

i am using the fermipy v1.0.1, and Sciencetool v2.0.8
please let me know, where i am doing wrong.

**Comment by Shruti0342** [comment]
Thanks for mentioning it. I will update then.

**Comment by henrikef** [comment]
Please re-open if you are still having this issue.
