### ISSUE TITLE
Is it mandatory having GTAnalysis() calling conda when executing ?

### ISSUE THREAD

**Issue by landriu** [fermiPy/fermipy#502]
Hello,

   I would like to know if it is necessary to call conda routines during execution of  GTAnalysis(), because
I meet the following error, coming from my local system organisation, where subprocesses loose the right
to launch conda commands : 

   gta = GTAnalysis( configFile, logging={'verbosity' : 3})
  File "/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 322, in __init__
    'ScienceTools version %s', fermipy.get_st_version())
  File "/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/site-packages/fermipy/__init__.py", line 37, in get_st_version
    vv = get_ft_conda_version()
  File "/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/site-packages/fermipy/__init__.py", line 62, in get_ft_conda_version
    lines = subprocess.check_output(['conda', 'list', '-f',  'fermitools']).split('\n')
  File "/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'conda'
Exception ignored in: <function GTAnalysis.__del__ at 0x7fe24e0099d0>
Traceback (most recent call last):
  File "/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 446, in __del__
    self.stage_output()
  File "/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 970, in stage_output
    elif not os.path.isdir(self.workdir):
  File "/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

  Is there a way not to call get_ft_conda_version() and get the information from an ancillary file for example ?

**Comment by landriu** [comment]
For the moment, it seems that I can live modifying :  
/dsm/manip/glast/anaconda3/envs/fermi-2.2.12/lib/python3.9/site-packages/fermipy/__init__.py

 with following lines : 
30 #orig    try:
 31 #orig        import ST_Version
 32 #orig        if hasattr(ST_Version, 'version'):
 33 #orig            vv = ST_Version.version()
 34 #orig        elif hasattr(ST_Version, 'get_git_version'):
 35 #orig            vv = ST_Version.get_git_version()
 36 #orig        if vv == "unknown":
 37 #orig            vv = get_ft_conda_version()
 38 #orig        return vv
 39 #orig    except ImportError:
 40 #orig        return ''
 41 #orig    except AttributeError:   
 42     import re
 43     from subprocess import Popen,PIPE
 44     cmd = 'env | grep FERMITOOLS'
 45     ft = Popen(cmd, shell=True, stdout=PIPE).stdout
 46     lines = ft.readlines()
 47     vv = str(re.split("[=']",str(lines[0].strip()))[2])
 48     return vv

   but I do not know if it has another implications.

Cheers,
   David Landriu
