### ISSUE TITLE
Multiple issues with gta.setup()

### ISSUE THREAD

**Issue by sindrsli** [fermiPy/fermipy#503]
Hi!

I am trying to reproduce some results from M. Ackermann et al 2018 ApJS 237 32. Thus I am using the 3FGL catalog and P8R2_SOURCE_V6 IRF in my analysis.

When using gta.setup() I run into errors. First error I think happens when running gtsrcmaps, I think. When generating a source map for 3FGL J1730.6-0357 i get the following warning of negative counts:

>>>2022-10-04 09:54:54 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1730.6-0357 25....................!
2022-10-04 09:54:54 INFO    GTBinnedAnalysis.run_gtapp(): Drm_Cache::update Measured counts < 0 3FGL J1730.6-0357 23 -5.37803e-12 1.52847e-11
2022-10-04 09:54:54 INFO    GTBinnedAnalysis.run_gtapp(): 25.9603 23.583 18.9044 13.4608 8.52409 4.82019 2.48172 1.18059 0.502435 0.195715 0.0700366 0.0229577 0.00692551 0.00188996 0.000460814 0.00010076 1.9789e-05 3.49882e-06 5.62836e-07 8.33421e-08 1.13516e-08 1.40615e-09 1.56671e-10 1.52847e-11

Furthermore, en error for galdiff source:
>>> 2022-10-04 11:10:40 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for galdiff 25....................!
2022-10-04 11:12:22 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for isodiff 25....................!
2022-10-04 11:12:22 INFO    GTBinnedAnalysis.run_gtapp(): ProjMap: extrapolated beyond the maximum energy for map cube file /cluster/apps/spack/2022a/software/fedora36/x86_64_v3/gcc-12.1.1/anaconda3-2021.05-xm3pfemcjrep4gogksbrmtoamsutvgkn/envs/fermi/share/fermitools/refdata/fermi/galdiffuse/gll_iem_v07.fits 698896 times.
2022-10-04 11:12:22 INFO    GTBinnedAnalysis.run_gtapp(): Caught St11range_error at the top level: Requested energy, 1e+06, lies outside the range of the input file, 34.171, 877938
2022-10-04 11:12:22 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 236.80 s

Then, probably because of the previous errors (?), I get an error when running GTBinnedAnalysis._create_binned_analysis(). There the error occurs in the header of srcmap_00.fits:

>>>RuntimeError: Cannot read keyword "NDSKEYS" in file "/work/olsen/_group/astroparticle/sindrsli/fermipy/ackermannpy/srcmap_00.fits" (CFITSIO ERROR 202: keyword not found in header)

When trying to delete e.g 3FGL J1730.6-0357 i get index error:

>>> gta.delete_source('3FGL J1730.6-0357')
2022-10-04 10:44:24 INFO    GTAnalysis.delete_source(): Deleting source 3FGL J1730.6-0357
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gudrun/sindrsli/.local/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1468, in delete_source
    self.free_norm(name, loglevel=logging.DEBUG)
  File "/home/gudrun/sindrsli/.local/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 2059, in free_norm
    name = self.get_source_name(name)
  File "/home/gudrun/sindrsli/.local/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 2208, in get_source_name
    if name not in self.like.sourceNames():
  File "/home/gudrun/sindrsli/.conda/envs/fermipy/lib/python3.9/site-packages/fermitools/SummedLikelihood.py", line 116, in sourceNames
    return self.components[0].sourceNames()
IndexError: list index out of range

I also have encountered errors when using gta.write_roi():

>>> gta.write_roi('setup_ackerman')
2022-10-04 10:28:33 INFO    GTBinnedAnalysis.write_xml(): Writing /work/olsen/_group/astroparticle/sindrsli/fermipy/ackermannpy/setup_ackerman_00.xml...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gudrun/sindrsli/.local/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 3726, in write_roi
    self.write_xml(xmlfile)
  File "/home/gudrun/sindrsli/.local/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 3273, in write_xml
    c.write_xml(xmlfile)
  File "/home/gudrun/sindrsli/.local/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5820, in write_xml
    self.like.writeXml(str(xmlfile))
AttributeError: 'NoneType' object has no attribute 'writeXml'

Any help with any of these errors will be gladly appreciated!

**Additional info:**

My config file: 
[config.zip](https://github.com/fermiPy/fermipy/files/9704459/config.zip)

Script I run for the setup:
>>>import yaml
config = yaml.load(open('config.yaml'),Loader=yaml.SafeLoader)
from fermipy.gtanalysis import GTAnalysis
gta = GTAnalysis('/work/olsen/_group/astroparticle/sindrsli/fermipy/ackermannpy/config.yaml',logging={'verbosity': 3})
gta.setup()

Full output of gta.setup():
>>> gta.setup()
2022-10-04 11:08:25 INFO    GTAnalysis.setup(): Running setup.
2022-10-04 11:08:25 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2022-10-04 11:08:25 INFO    GTBinnedAnalysis._select_data(): Skipping data selection.
2022-10-04 11:08:25 INFO    GTBinnedAnalysis._create_ltcube(): Skipping LT Cube.
2022-10-04 11:08:26 INFO    GTBinnedAnalysis._create_expcube(): Skipping gtexpcube.
2022-10-04 11:08:26 INFO    GTBinnedAnalysis.run_gtapp(): Running gtsrcmaps.
2022-10-04 11:08:26 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtsrcmaps scfile=spacecraft.fits sctable="SC_DATA" expcube=/work/olsen/_group/astroparticle/sindrsli/fermipy/ackermannpy/ltcube_00.fits cmap=/work/olsen/_group/astroparticle/sindrsli/fermipy/ackermannpy/ccube_00.fits srcmdl=/work/olsen/_group/astroparticle/sindrsli/fermipy/ackermannpy/srcmdl_00.xml bexpmap=/work/olsen/_group/astroparticle/sindrsli/fermipy/ackermannpy/bexpmap_00.fits wmap=none outfile=/work/olsen/_group/astroparticle/sindrsli/fermipy/ackermannpy/srcmap_00.fits irfs="P8R2_SOURCE_V6" evtype=32 convol=yes resample=yes rfactor=2 minbinsz=0.05 ptsrc=yes psfcorr=yes emapbnds=no edisp_bins=-1 copyall=no chatter=3 clobber=yes debug=no gui=no mode="ql"
2022-10-04 11:08:26 INFO    GTBinnedAnalysis.run_gtapp(): This is gtsrcmaps version HEAD
2022-10-04 11:08:26 INFO    GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6 (PSF)
2022-10-04 11:08:26 INFO    GTBinnedAnalysis.run_gtapp(): event_types:  5
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J1720.3-0428
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J1722.7-0415
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J1725.0-0513
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J1727.6-0654
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J1709.5-0335
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J1730.6-0357
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J1704.4-0528
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J1709.4-0917
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J1729.9-0859
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J1744.3-0353
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named isodiff
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named galdiff
2022-10-04 11:08:31 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1704.4-0528 25....................!
2022-10-04 11:08:32 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1709.4-0917 25....................!
2022-10-04 11:08:33 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1709.5-0335 25....................!
2022-10-04 11:08:34 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1720.3-0428 25....................!
2022-10-04 11:08:35 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1722.7-0415 25....................!
2022-10-04 11:08:36 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1725.0-0513 25....................!
2022-10-04 11:08:37 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1727.6-0654 25....................!
2022-10-04 11:08:37 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1729.9-0859 25....................!
2022-10-04 11:08:38 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1730.6-0357 25....................!
2022-10-04 11:08:38 INFO    GTBinnedAnalysis.run_gtapp(): Drm_Cache::update Measured counts < 0 3FGL J1730.6-0357 23 -5.37803e-12 1.52847e-11
2022-10-04 11:08:38 INFO    GTBinnedAnalysis.run_gtapp(): 25.9603 23.583 18.9044 13.4608 8.52409 4.82019 2.48172 1.18059 0.502435 0.195715 0.0700366 0.0229577 0.00692551 0.00188996 0.000460814 0.00010076 1.9789e-05 3.49882e-06 5.62836e-07 8.33421e-08 1.13516e-08 1.40615e-09 1.56671e-10 1.52847e-11
2022-10-04 11:08:39 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J1744.3-0353 25....................!
2022-10-04 11:10:40 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for galdiff 25....................!
2022-10-04 11:12:22 INFO    GTBinnedAnalysis.run_gtapp(): Generating SourceMap for isodiff 25....................!
2022-10-04 11:12:22 INFO    GTBinnedAnalysis.run_gtapp(): ProjMap: extrapolated beyond the maximum energy for map cube file /cluster/apps/spack/2022a/software/fedora36/x86_64_v3/gcc-12.1.1/anaconda3-2021.05-xm3pfemcjrep4gogksbrmtoamsutvgkn/envs/fermi/share/fermitools/refdata/fermi/galdiffuse/gll_iem_v07.fits 698896 times.
2022-10-04 11:12:22 INFO    GTBinnedAnalysis.run_gtapp(): Caught St11range_error at the top level: Requested energy, 1e+06, lies outside the range of the input file, 34.171, 877938
2022-10-04 11:12:22 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtsrcmaps. Execution time: 236.80 s
2022-10-04 11:12:22 INFO    GTBinnedAnalysis.setup(): Finished setup for component 00
2022-10-04 11:12:22 INFO    GTBinnedAnalysis._create_binned_analysis(): Creating BinnedAnalysis for component 00.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gudrun/sindrsli/.local/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1090, in setup
    self._create_likelihood()
  File "/home/gudrun/sindrsli/.local/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1117, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/home/gudrun/sindrsli/.local/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5457, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/home/gudrun/sindrsli/.conda/envs/fermipy/lib/python3.9/site-packages/fermitools/BinnedAnalysis.py", line 71, in __init__
    self._createObservation(srcMaps, expCube, self.irfs)
  File "/home/gudrun/sindrsli/.conda/envs/fermipy/lib/python3.9/site-packages/fermitools/BinnedAnalysis.py", line 74, in _createObservation
    self._respFuncs.load_with_event_types(irfs, "", self.srcMaps, "")
  File "/home/gudrun/sindrsli/.conda/envs/fermipy/lib/python3.9/site-packages/fermitools/pyLikelihood.py", line 6594, in load_with_event_types
    return _pyLikelihood.ResponseFunctions_load_with_event_types(self, respFuncs, respBase, filename, extname)
RuntimeError: Cannot read keyword "NDSKEYS" in file "/work/olsen/_group/astroparticle/sindrsli/fermipy/ackermannpy/srcmap_00.fits" (CFITSIO ERROR 202: keyword not found in header)

 - OS: Fedora Linux 36
 - Linux #1 SMP PREEMPT_DYNAMIC Tue Sep 20 15:15:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- fermipy 1.2
- fermitools 2.2.0

**Comment by sindrsli** [comment]
Hi!

Thanks for the quick reply.

The fssc helpdesk told me that there should be no problem using 1TeV in the config.yaml file.

Now the remaining error is for the srcmap_00.fits file.

>RuntimeError: Cannot read keyword "NDSKEYS" in file "/work/olsen/_group/astroparticle/sindrsli/fermipy/ackermannpy/srcmap_00.fits" (CFITSIO ERROR 202: keyword not found in header)

I am doing the same analysis for the whole fermi LAT data set with 4FGL, and this error does not occur in that analysis, using the same versions of fermipy and fermitools.

Any ideas?
