### ISSUE TITLE
Installation under micromamba

### ISSUE THREAD

**Issue by jeget** [fermiPy/fermipy#511]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In the installation instructions, it is recommended to use mamba, and anaconda is presumed to be in place. I have micromamba instead of anaconda, and I installed fermipy successfully, it seems to work. However, when I first started it, I got an error

> Traceback (most recent call last):
  File "/home/bulat/micromamba/envs/fermipy/lib/python3.9/site-packages/fermipy/__init__.py", line 60, in get_ft_conda_version
    lines = subprocess.check_output(['conda', 'list', '-f',  'fermitools']).decode().split('\n')
  File "/home/bulat/micromamba/envs/fermipy/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/bulat/micromamba/envs/fermipy/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/bulat/micromamba/envs/fermipy/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/bulat/micromamba/envs/fermipy/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'

**Describe the solution you'd like**
I'd like fermipy to install and work under micromamba, too.

**Describe alternatives you've considered**
To prevent the error, in fermipy/\_\_init\_\_.py, I changed
`lines = subprocess.check_output(['conda', 'list', '-f',  'fermitools']).decode().split('\n')`
to
`lines = subprocess.check_output(['/home/bulat/.local/bin/micromamba', 'list', 'fermitools']).decode().split('\n')`
which made fermipy work. I guess, conda version is not critically important. But this is of course just a rude solution. Maybe the installation itself should depend on whether conda/mamba or micromamba is used?

**Comment by henrikef** [comment]
Hi @jeget ! Yes, this seems like a reasonable feature. Would you like to try and implement a more general way of determining the fermitools version yourself? I can assist you with making a pull request if you'd like.
