### ISSUE TITLE
Installing fermipy from source raise error

### ISSUE THREAD

**Issue by MRegeard** [fermiPy/fermipy#537]
Hi, 

I try to install fermipy from the source code, but it raise the following error when I run `python setup.py install` :

```
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/dist.py:561: UserWarning: The version specified ('unknown') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_normalization.py:93: SetuptoolsDeprecationWarning: Invalid version: 'unknown'.
        !!


        ###################
        # Invalid version #
        ###################
        'unknown' is not valid according to PEP 440.

        Please make sure specify a valid version for your package.
        Also note that future releases of setuptools may halt the build process
        if an invalid version is given.
        

!!
        
  warnings.warn(cleandoc(msg), SetuptoolsDeprecationWarning)
Traceback (most recent call last):
  File "/Users/mregeard/Workspace/dev/code/fermipy/fermipy/setup.py", line 5, in <module>
    setup(
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 92, in finalize_options
    ei_cmd = self.ei_cmd = self.get_finalized_command("egg_info")
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 220, in finalize_options
    parsed_version = packaging.version.Version(self.egg_version)
  File "/Users/mregeard/anaconda3/envs/fermipy-dev/lib/python3.9/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'unknown'
```

Is it a known issue, and do you know how to make it work ?

**Comment by henrikef** [comment]
Hi Maxime, please try installing via pip. pip install fermipy for the
latest release. pip install local/path/to/fermipy to install a local
version from disk. Fermitools should be installed first.

**Comment by henrikef** [comment]
That's odd. Did you get any other output before the error message? Can you post the full log here please? (Also, just to be sure, did you `conda activate fermipy-dev` before the `pip install` step?)
