### ISSUE TITLE
Facing issue while analyzing a few 3FGL sources

### ISSUE THREAD

**Issue by AnuvabAstro** [fermiPy/fermipy#556]
Hi,
I am trying to generate a source model for sources using 3FGL catalog, and for a few cases, I am getting the following error:
Traceback (most recent call last):
  File "/zfs/astrohe/anuvab/stacking_fresh_run/run_8/run.py", line 205, in <module>
    main(sys.argv)
  File "/zfs/astrohe/anuvab/stacking_fresh_run/run_8/run.py", line 96, in main
    gta.setup()
  File "/zfs/astrohe/Software/fermipy_1.2/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1090, in setup
    self._create_likelihood()
  File "/zfs/astrohe/Software/fermipy_1.2/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1117, in _create_likelihood
    c._create_binned_analysis(srcmdl)
  File "/zfs/astrohe/Software/fermipy_1.2/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5457, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/zfs/astrohe/Software/fermipy_1.2/lib/python3.9/site-packages/fermitools/BinnedAnalysis.py", line 71, in __init__
    self._createObservation(srcMaps, expCube, self.irfs)
  File "/zfs/astrohe/Software/fermipy_1.2/lib/python3.9/site-packages/fermitools/BinnedAnalysis.py", line 74, in _createObservation
    self._respFuncs.load_with_event_types(irfs, "", self.srcMaps, "")
  File "/zfs/astrohe/Software/fermipy_1.2/lib/python3.9/site-packages/fermitools/pyLikelihood.py", line 6594, in load_with_event_types
    return _pyLikelihood.ResponseFunctions_load_with_event_types(self, respFuncs, respBase, filename, extname)
RuntimeError: Cannot read keyword "NDSKEYS" in file "/zfs/astrohe/anuvab/stacking_fresh_run/run_8/model_1GeV_1TeV_complex_with_ts/3FGL_J1254.9-4423/srcmap_00.fits" (CFITSIO ERROR 202: keyword not found in header)

Could you kindly help me understand what is happening? I am using a ltcube file with a cut at 90 degrees. Here are a few more details:
irfs : 'P8R3_SOURCE_V2'
isodiff: iso_P8R3_SOURCE_V3_v1.txt
galdiff: gll_iem_v07.fits

I am happy to provide further details if necessary.

**Comment by omodei** [comment]
Hi! I am afraid there are not enough information. Can you provide the configuration file and the code you are running that produce this error?
