### ISSUE TITLE
FERMI LAT data analysis using fermipy.

### ISSUE THREAD

**Issue by NithyaSathyan** [fermiPy/fermipy#559]
## Data Analysis Question

I have installed fermipy using conda. The following script is used to run the analysis.

from fermipy.gtanalysis import GTAnalysis
gta = GTAnalysis('config.yaml',logging={'verbosity': 3})
gta.setup()
gta.free_sources(distance=3.0,pars='norm')
gta.free_source('galdiff')
gta.free_source('isodiff')
gta.free_sources(minmax_ts=[10,None],pars='norm')
gta.free_source('4FGL J0650.7+2503')
gta.fit()
gta.write_roi('fit_model')
import numpy as np
sed=gta.sed('4FGL J0650.7+2503', make_plots=True)

 After running this, I encounter an error of the type given below
2023-12-28 08:52:15 INFO    GTAnalysis.__init__(): 
--------------------------------------------------------------------------------
fermipy version 1.2.0 
ScienceTools version 2.2.0
2023-12-28 08:52:17 INFO    GTAnalysis.setup(): Running setup.
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtselect infile=/home/dell/data backup ubuntu dell mint/Documents/low_z_BLLACs/1H1914-194/evfile_00.txt outfile=/home/dell/data backup ubuntu dell mint/Documents/low_z_BLLACs/1H1914-194/ft1_00.fits ra=289.4383850097656 dec=-19.36280059814453 rad=7.5710678118654755 tmin=239557417.0 tmax=686188805.0 emin=1000.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): Parameter "infile" duplicated on command line.
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): Parameter "infile" duplicated on command line.
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtselect; Ape exception code 19 (at /home/conda/feedstock_root/build_artifacts/fermitools_1655479216784/work/src/hoops/src/hoops_ape.cxx: 435)
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtselect. Execution time: 0.12 s
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): Running gtltcube.
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtltcube evfile="/home/dell/data backup ubuntu dell mint/Documents/low_z_BLLACs/1H1914-194/ft1_00.fits" evtable="EVENTS" scfile=L2312261019265A50769872_SC00.fits sctable="SC_DATA" outfile=/home/dell/data backup ubuntu dell mint/Documents/low_z_BLLACs/1H1914-194/ltcube_00.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=90.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): Parameter "evfile" duplicated on command line.
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): Parameter "evfile" duplicated on command line.
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtltcube; Ape exception code 19 (at /home/conda/feedstock_root/build_artifacts/fermitools_1655479216784/work/src/hoops/src/hoops_ape.cxx: 435)
2023-12-28 08:52:17 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 0.12 s
Traceback (most recent call last):
  File "/home/dell/data backup ubuntu dell mint/Documents/low_z_BLLACs/1H1914-194/xx.py", line 3, in <module>
    gta.setup()
  File "/home/dell/anaconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1087, in setup
    c.setup(overwrite=overwrite)
  File "/home/dell/anaconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5176, in setup
    self._ltc = LTCube.create(self.files['ltcube'])
  File "/home/dell/anaconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/ltcube.py", line 192, in create
    ltc = cls.create_from_fits(files[0])
IndexError: list index out of range

How do I fix this? Thanks in advance.

**Comment by omodei** [comment]
Same issue of the path of your previous issue (#560)
