### ISSUE TITLE
Errors with gammapy and astropy

### ISSUE THREAD

**Issue by anyabua** [fermiPy/fermipy#579]
Hi all,
Sorry for disturbing you, but i'm having issues with gammapy and astropy. It seems like I might not have the correct versions of scipy/or other packages.
I'm running gta.setup() and I'm using gammapy = 1.1 with scipy version = 1.11.4 and astropy = 5.3.4. I'm getting this error message:

Traceback (most recent call last):
  File "/mnt/zfsusers/anyabua/mambaforge/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5144, in setup
    self._bexp = Map.read(self.files['bexpmap'], hdu=hpxhduname)
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/maps/core.py", line 240, in read
    return Map.from_hdulist(
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/maps/core.py", line 308, in from_hdulist
    map_type = Map._get_map_type(hdulist, hdu)
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/maps/core.py", line 339, in _get_map_type
    header = hdu_list[hdu_name].header
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 390, in __getitem__
    super().__getitem__, self._positive_index_of(key)
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 857, in _positive_index_of
    index = self.index_of(key)
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 839, in index_of
    raise KeyError(f"Extension {key!r} not found.")
KeyError: "Extension 'HPXEXPOSURES' not found."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/extraspace/anyabua/FermiMapMaking/new_all_lat/fermipy_run.py", line 6, in <module>
    gta.setup()
  File "/mnt/zfsusers/anyabua/mambaforge/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1085, in setup
    c.setup(overwrite=overwrite)
  File "/mnt/zfsusers/anyabua/mambaforge/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5146, in setup
    self._bexp = Map.read(self.files['bexpmap'])
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/maps/core.py", line 240, in read
    return Map.from_hdulist(
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/maps/core.py", line 315, in from_hdulist
    return cls_out.from_hdulist(
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/maps/wcs/core.py", line 142, in from_hdulist
    wcs_map = cls.from_hdu(hdu, hdu_bands, format=format)
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/maps/wcs/ndmap.py", line 88, in from_hdu
    geom = WcsGeom.from_header(hdu.header, hdu_bands, format=format)
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/maps/wcs/geom.py", line 485, in from_header
    axes = MapAxes.from_table_hdu(hdu_bands, format=format)
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/maps/axes.py", line 1962, in from_table_hdu
    return cls.from_table(table, format=format)
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/maps/axes.py", line 1980, in from_table
    from gammapy.irf.io import IRF_DL3_AXES_SPECIFICATION
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/irf/__init__.py", line 11, in <module>
    from .psf import (
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/irf/psf/__init__.py", line 1, in <module>
    from .kernel import PSFKernel
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/irf/psf/kernel.py", line 6, in <module>
    from gammapy.modeling.models import PowerLawSpectralModel
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/modeling/__init__.py", line 4, in <module>
    from .fit import Fit
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/modeling/fit.py", line 15, in <module>
    from .scipy import confidence_scipy, optimize_scipy
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/modeling/scipy.py", line 5, in <module>
    from gammapy.utils.roots import find_roots
  File "/mnt/users/anyabua/.local/lib/python3.9/site-packages/gammapy/utils/roots.py", line 9, in <module>
    BAD_RES = RootResults(root=np.nan, iterations=0, function_calls=0, flag=0)
TypeError: __init__() missing 1 required positional argument: 'method'

Updating to gammapy = 1.2 doesn't solve the problem either. Any help would be greatly appreciated. 
My fermipy version is 1.2.2, my fermitools version is 2.2.0 and my fermitools-data version is 0.18

**Comment by omodei** [comment]
Hi Anya, your environment seems fine to me, but from the error log I am not sure what is the calling sequence. Can you send me the part of your code which is causing the exception?

**Comment by anyabua** [comment]
@omodei Hi, thank you so much for responding! All i'm running is 

gta = GTAnalysis('config.yaml',logging={'verbosity' : 4})                                                                                                                    
gta.setup()   
These are the contents of my configuration file: 

binning:
  coordsys: GAL
  enumbins: 1
  hpx_ebin: true
  hpx_order: 9
  hpx_ordering_scheme: RING
  projtype: HPX
  roiwidth: 360
data:
  evfile: /mnt/extraspace/anyabua/FermiMapMaking/new_all_lat/lat_processed_ec2048_et56_zmax90_gti.fits
  ltcube: /mnt/extraspace/anyabua/FermiMapMaking/new_all_lat/lat_processed_ec2048_et56_zmax90_ltcube.fits
  scfile: /mnt/extraspace/anyabua/FermiMapMaking/new_all_lat/lat_spacecraft_merged.fits
fileio:
  outdir: /mnt/extraspace/anyabua/FermiMapMaking/new_all_lat/
  savefits: false
  scratchdir: /mnt/extraspace/anyabua/FermiMapMaking/new_all_lat/
  usescratch: false
  workdir: /mnt/extraspace/anyabua/FermiMapMaking/new_all_lat/
gtlike:
  irfs: P8R3_SOURCEVETO_V3
  wmap: /mnt/extraspace/anyabua/FermiMapMaking/masks/full_mask.fits
model:
  catalogs:
  - /mnt/extraspace/anyabua/FermiMapMaking/all_lat/srcmodel.xml
selection:
  dec: 0
  emax: 5000
  emin: 2000
  evclass: 2048
  evtype: 56
  filter: "'DATA_QUAL>0 && LAT_CONFIG==1'"
  ra: 0
  radius: 180
  roicut: 'no'
  tmax: 729411879.416944
  tmin: 239557417.494176
  zmax: 90

**Comment by facero** [comment]
Hi,
don't know if your specific error is related but I've just tested to install fermipy with gammapy 1.2 and astropy 6.0.0 (not 6.0.1) and my gta.setup(), ROI fit, SED, TS map worked just fine.

I see that you had gammapy 1.2 but astropy 5.3.

Maybe unrelated but worth a try

**Comment by omodei** [comment]
@anyabua : Can this issue be closed? Did you fix your problem?
