### ISSUE TITLE
ValueError: Maximum allowed size exceeded while making SED

### ISSUE THREAD

**Issue by Adinimal** [fermiPy/fermipy#581]
**Describe the bug**
A clear and concise description of what the bug is. What data are you using and how was it obtained? 
I am using Fermi-LAT data of a source 4FGLJ0649.5-3139. During period MJD 55718-55802, I am getting this error while trying to generate the SED (rom 100 MeV to 300 GeV). While for other periods, I did not have any issue. 
This is the error:
Traceback (most recent call last):
  File "/var/spool/slurmd/job43387301/slurm_script", line 327, in <module>
    main(sys.argv)
  File "/var/spool/slurmd/job43387301/slurm_script", line 168, in main
    sed = gta.sed(srcname, make_plots=True)
  File "/sdf/home/../miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/sed.py", line 108, in sed
    self._plotter.make_sed_plots(o, **config)
  File "/sdf/home/../miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/plotting.py", line 1287, in make_sed_plots
    p.plot(showlnl=True)
  File "/sdf/home/../miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/plotting.py", line 874, in plot
    return SEDPlotter.plot_sed(self.sed, showlnl, **kwargs)
  File "/sdf/home/../miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/plotting.py", line 866, in plot_sed
    SEDPlotter.plot_lnlscan(sed, **kwargs)
  File "/sdf/home/../miniforge3/envs/fermipy/lib/python3.9/site-packages/fermipy/plotting.py", line 705, in plot_lnlscan
    fluxEdges = np.arange(fmin, fmax, 0.01)
ValueError: Maximum allowed size exceeded
*NOTE:* This is for fermipy bug reports and not for questions about data analysis or issues with fermitools.

**To Reproduce**

Please provide enough information for someone else to reporoduce this bug. That means e.g. a script + (links to) necessary files + any command line options, or an ipython notebook or something similar.

**Expected behavior**

**Log files**
Add log files or copy & paste the entire output on the terminal or jupyer notebook cell.

**Environment (please complete the following information):**
 - OS: (e.g. MacOS Monterey version 12.3.1)
 - Output of `uname -a`: Linux sdfiana009 4.18.0-372.32.1.el8_6.x86_64
 - fermipy version 1.2.0

**Additional context**

**Comment by omodei** [comment]
Hi! Can you try the same with ferry 1.2.2 installed via pypi. Also, can you send us a script that we can run to reproduce the error?

**Comment by omodei** [comment]
@ndilalla suggested also to try to ask for more memory when submitting to slurm at SLAC. It might be that the default is too small.
