### ISSUE TITLE
lightcurve(): OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by navaneethnpk** [fermiPy/fermipy#590]
## Data Analysis Question

I was trying to generate a lightcurve spanning ~15 years of Fermi data. However, I encountered an error after processing 340 bins. The error message indicated that there were 'Too many open files' during the FermiPy analysis, exceeding the operating system's limit (which is 1024 in my case).

**What's the best approach to address this? Should I analyze the data in segments rather than processing it all at once?**

```
2024-04-30 05:41:27 INFO    lightcurve_444528001_445132801 GTAnalysis._process_lc_bin(): Finished time range 444528001 445132801
2024-04-30 05:41:28 INFO    lightcurve_445132801_445737601 GTAnalysis._process_lc_bin(): Fitting time range 445132801 445737601
Analysis failed in time range 445132801 445737601
(<class 'OSError'>, OSError(24, 'Too many open files'), <traceback object at 0x7ff5215c26c0>)
2024-04-30 05:41:28 ERROR   GTAnalysis._make_lc(): Fit failed in bin 336 in range 445132801 445737601.
Analysis failed in time range 445737601 446342401
(<class 'OSError'>, OSError(24, 'Too many open files'), <traceback object at 0x7ff520eacac0>)
2024-04-30 05:41:28 INFO    lightcurve_445737601_446342401 GTAnalysis.stage_output(): Staging files to /home/navaneeth/Works/mrk421/mrk421_LC/lightcurve_445737601_446342401
Exception ignored in: <function GTAnalysis.__del__ at 0x7ff53a161310>
Traceback (most recent call last):
  File "/home/navaneeth/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 446, in __del__
    self.stage_output()
  File "/home/navaneeth/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 980, in stage_output
    for c in self.components:
  File "/home/navaneeth/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 487, in components
    return self._components
AttributeError: 'GTAnalysis' object has no attribute '_components'
2024-04-30 05:41:28 ERROR   GTAnalysis._make_lc(): Fit failed in bin 337 in range 445737601 446342401.
Analysis failed in time range 446342401 446947201
(<class 'OSError'>, OSError(24, 'Too many open files'), <traceback object at 0x7ff5212be1c0>)
Exception ignored in: <function GTAnalysis.__del__ at 0x7ff53a161310>
Traceback (most recent call last):
  File "/home/navaneeth/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 446, in __del__
  File "/home/navaneeth/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 976, in stage_output
OSError: [Errno 24] Too many open files: '/home/navaneeth/Works/mrk421/mrk421_LC'
2024-04-30 05:41:28 ERROR   GTAnalysis._make_lc(): Fit failed in bin 338 in range 446342401 446947201.
Traceback (most recent call last):
  File "/home/navaneeth/Works/mrk421/mrk421_LC/run_lc.py", line 23, in <module>
  File "/home/navaneeth/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/lightcurve.py", line 290, in lightcurve
  File "/home/navaneeth/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/lightcurve.py", line 451, in _make_lc
  File "/home/navaneeth/miniconda3/envs/fermipy/lib/python3.9/site-packages/fermipy/lightcurve.py", line 149, in _process_lc_bin
OSError: [Errno 24] Too many open files: '/home/navaneeth/Works/mrk421/mrk421_LC/lightcurve_446947201_447552001/config.yaml'
```

```
(base) navaneeth@std:~$ ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 4126163
max locked memory           (kbytes, -l) 132051708
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 4126163
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```
### To reproduce
- config.yaml:
```
data:
  evfile : pfiles.dat
  scfile : sfiles.dat

binning:
  roiwidth   : 10.0
  binsz      : 0.1
  binsperdec : 8

selection :
  emin : 100
  emax : 500000
  zmax    : 90
  evclass : 128
  evtype  : 3
  tmin    : 241920001
  tmax    : 730771205
  target : '4FGL J1104.4+3812'

gtlike:
  edisp : True
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable : ['isodiff','galdiff']

model:
  src_roiwidth : 15.0
  galdiff  : '/home/navaneeth/Works/MY_FERMI_DIR/gll_iem_v07.fits'
  isodiff  : '/home/navaneeth/Works/MY_FERMI_DIR/iso_P8R3_SOURCE_V3_v1.txt'
  catalogs : '/home/navaneeth/Works/MY_FERMI_DIR/gll_psc_v34.fit'
```

- Code:
```
import numpy as np
from fermipy.gtanalysis import GTAnalysis
import pickle

gta = GTAnalysis('config.yaml', logging={'verbosity': 3})
gta.setup()
gta.optimize()

gta.free_sources(False)
gta.free_sources(distance=3.0, pars='norm')
gta.free_source('galdiff')
gta.free_source('isodiff')
gta.free_source('4FGL J1104.4+3812')
gta.fit()
gta.write_roi('fit_model', make_plots=True)

lc = gta.lightcurve('4FGL J1104.4+3812', binsz=86400.*7.0, free_radius=3.0)
with open('lightcurve.pkl', 'wb') as f:
    pickle.dump(lc, f)
```

**Comment by ndilalla** [comment]
Thanks @navaneethnpk for reporting this issue. This looks like a limitation due to your operating system. Could you post here the output of the bash command `ulimit -n`?

**Comment by navaneethnpk** [comment]
@ndilalla 
```
(base) navaneeth@std:~$ ulimit -n
1024
```
What is the solution for my case?  
How many files are opening while running a fermipy script? (I can batch my analysis according to the number)

**Comment by ndilalla** [comment]
I am not sure. Given the current limit and the bin where `fermipy` fails, I would guess something around 3 files/bin. Can you try increasing the limit by running for instance `ulimit -n 10240`? This would allow you to run x10 bins. It's just a workaround as I/O files should be closed right after being opened at the fermipy level.
