### ISSUE TITLE
gta.setup() IndexError

### ISSUE THREAD

**Issue by ranaosmanawad** [fermiPy/fermipy#599]
## Data Analysis Question

I keep getting the following error. I've ran a nearly identical analysis on the vela pulsar to test it out and had no issues, but now it isn't working. I believe its the same error as the one in Issue #560, but I don't have any spaces in my directory names.

fermipy version 1.2.2
ScienceTools version 2.2.0
2024-07-08 15:55:10 INFO    GTAnalysis.setup(): Running setup.
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.setup(): Running setup for component 00
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): Running gtselect.
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtselect infile=/home/osman/J00948+0022/data/J0948events.lst outfile=/home/osman/J00948+0022/outputs/ft1_00.fits ra=147.239 dec=0.3737 rad=7.5710678118654755 tmin=239557417.0 tmax=334165417.0 emin=100.0 emax=300000.0 zmin=0.0 zmax=90.0 evclass=128 evtype=3 convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=3 clobber=yes debug=no gui=no mode="ql"
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): This is gtselect version HEAD
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): Caught St13runtime_error at the top level: File not found: /home/osman/J00948+0022/data/J0948events.lst
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtselect. Execution time: 0.21 s
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): Running gtmktime.
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtmktime scfile=/home/osman/J00948+0022/data/L24070800525804F0BF7E68_SC00.fits sctable="SC_DATA" filter="DATA_QUAL>0 && LAT_CONFIG==1" roicut=no evfile=/home/osman/J00948+0022/outputs/ft1_00.fits evtable="EVENTS" outfile="/home/osman/J00948+0022/outputs/ft1_filtered_00.fits" apply_filter=yes overwrite=no header_obstimes=yes tstart=0.0 tstop=0.0 gtifile="default" chatter=2 clobber=yes debug=no gui=no mode="ql"
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): Caught N3tip12TipExceptionE at the top level: File not found: /home/osman/J00948+0022/outputs/ft1_00.fits
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtmktime. Execution time: 0.16 s
mv: cannot stat ‘/home/osman/J00948+0022/outputs/ft1_filtered_00.fits’: No such file or directory
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): Running gtltcube.
2024-07-08 15:55:10 INFO    GTBinnedAnalysis.run_gtapp(): time -p gtltcube evfile="/home/osman/J00948+0022/outputs/ft1_00.fits" evtable="EVENTS" scfile=/home/osman/J00948+0022/data/L24070800525804F0BF7E68_SC00.fits sctable="SC_DATA" outfile=/home/osman/J00948+0022/outputs/ltcube_00.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=90.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
2024-07-08 15:55:11 INFO    GTBinnedAnalysis.run_gtapp(): Caught St13runtime_error at the top level: File not found: /home/osman/J00948+0022/outputs/ft1_00.fits
2024-07-08 15:55:11 INFO    GTBinnedAnalysis.run_gtapp(): Finished gtltcube. Execution time: 0.19 s
Traceback (most recent call last):
  File "/home/osman/J0948+0022/J0948+0022.py", line 3, in <module>
    gta.setup()
  File "/home/osman/.conda/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 1087, in setup
    c.setup(overwrite=overwrite)
  File "/home/osman/.conda/envs/fermipy/lib/python3.9/site-packages/fermipy/gtanalysis.py", line 5176, in setup
    self._ltc = LTCube.create(self.files['ltcube'])
  File "/home/osman/.conda/envs/fermipy/lib/python3.9/site-packages/fermipy/ltcube.py", line 192, in create
    ltc = cls.create_from_fits(files[0])
IndexError: list index out of range

### **To reproduce**

*configuration file*

data:
  evfile : /home/osman/J00948+0022/data/J0948events.lst
  scfile : /home/osman/J00948+0022/data/L24070800525804F0BF7E68_SC00.fits

binning:
  roiwidth   : 10
  binsz      : 0.1
  binsperdec : 10

selection :
  emin : 100
  emax : 300000
  zmax    : 90
  evclass : 128
  evtype  : 3
  ra: 147.239
  dec: 0.3737
  tmin: 239557417
  tmax: 334165417
  filter : 'DATA_QUAL>0 && LAT_CONFIG==1'

gtlike:
  edisp : True
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable : ['isodiff']
  edisp_bins : -1

lightcurve:
  binsz: 86400.0

model:
  src_roiwidth : 25
  galdiff  : '$FERMI_DIFFUSE_DIR/gll_iem_v07.fits'
  isodiff  : 'iso_P8R3_SOURCE_V3_v1.txt'
  catalogs : ['4FGL-DR3']

plotting:
  label_ts_threshold : 9

optimizer:
  optimizer: NEWMINUIT

fileio:
  outdir : /home/osman/J00948+0022/outputs

*analysis script*

from fermipy.gtanalysis import GTAnalysis
gta = GTAnalysis('J0948+0022config.yaml',logging={'verbosity' : 3})
gta.setup()
gta.optimize()
gta.free_sources(distance=3.0,pars='norm')
gta.free_source('galdiff')
gta.free_source('isodiff')
gta.free_sources(minmax_ts=[25,None],pars='norm')
gta.fit()
gta.write_roi('J0948_model')
model = {'SpatialModel' : 'PointSource', 'Index' : 2.25, 'SpectrumType' : 'PowerLaw'}
m0 = gta.residmap('J0948_model', model=model, make_plots=True)
m1 = gta.tsmap('J0948_model', model=model, make_plots=True)
gta.sed('PMN J0948+0022', make_plots=True)

**Any help would be greatly appreciated!**

**Comment by omodei** [comment]
Can you try to use a different path name, without the "+" sign? Maybe /home/osman/J00948p0022 ?
