### ISSUE TITLE
python not setting up a config file due to 'srcmap_00.fits' file not found

### ISSUE THREAD

**Issue by heatdeath707** [fermiPy/fermipy#93]
Hi, I am trying to replicate the draco tutorial with my own code. I am having trouble setting up a configuration file because of a file not found error for "srcmap_00.fits".
I am new to fermipy so please bear with me, i executed the following code:

> > > import os, matplotlib, numpy
> > > from fermipy.gtanalysis import GTAnalysis
> > > gta=GTAnalysis('config.yaml')
> > > gta.setup()

The computer was spitting text, and everything was going beautifully until
RuntimeError: File not found: /home/heatdeath/fermi_science/science/srcmap_00.fits

I googled srcmap_00.fits and only found another github issue. I tried to see if it would work at gtsrcmaps but I could not figure out what a srcmap is and why an XML model is required. 

Any help would be appreciated.
Thanks

**Comment by woodmd** [comment]
I'll need a bit more information to debug the issue you're having.  Can you provide the log file for the analysis you were running?

**Comment by heatdeath707** [comment]
I executed the code I wrote above and received the following output:

>>> gta.setup()
2016-10-25 22:20:33 INFO     GTAnalysis.setup(): Running setup
2016-10-25 22:20:33 INFO     GTBinnedAnalysis.setup(): Running setup for Analysis Component: 00
2016-10-25 22:20:38 INFO     GTBinnedAnalysis.run_gtapp(): Running gtsrcmaps
2016-10-25 22:20:39 INFO     GTBinnedAnalysis.run_gtapp(): time -p /home/heatdeath/fermi_science/ScienceTools-v10r0p5-fssc-20150518A-source/x86_64-unknown-linux-gnu-libc2.19-0/bin/gtsrcmaps scfile=All_sky_Thea-ft2-30s.fits sctable="SC_DATA" expcube=test_ltcube1.fits cmap=/home/heatdeath/fermi_science/science/ccube_00.fits srcmdl=/home/heatdeath/fermi_science/science/srcmdl_00.xml bexpmap=/home/heatdeath/fermi_science/science/bexpmap_00.fits outfile=/home/heatdeath/fermi_science/science/srcmap_00.fits irfs="P8R2_SOURCE_V6" evtype=3 convol=yes resample=yes rfactor=2 minbinsz=0.05 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=3 clobber=yes debug=no gui=no mode="ql"
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): This is gtsrcmaps version ScienceTools-v10r0p5-fssc-20150518
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Using evtype=3 (i.e., FRONT/BACK irfs)
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): ResponseFunctions::load: IRF used: P8R2_SOURCE_V6
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): event_types:  0  1
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J2357.3-0150
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J0006.2+0135
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J0016.3-0013
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J2338.1-0229
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J2338.7+0251
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J0014.3-0455
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J0020.9+0323
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J2335.1-0133
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J0017.6-0512
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J0009.1+0630
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J2344.4+0549
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J0024.4+0350
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J2339.6-0533
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J2346.7+0705
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J0017.2-0643
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named 3FGL J0022.5+0608
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named isodiff
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Creating source named galdiff
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J0006.2+0135....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J0009.1+0630....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J0014.3-0455....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J0016.3-0013....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J0017.2-0643....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J0017.6-0512....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J0020.9+0323....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J0022.5+0608....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J0024.4+0350....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J2335.1-0133....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J2338.1-0229....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J2338.7+0251....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J2339.6-0533....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J2344.4+0549....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J2346.7+0705....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for 3FGL J2357.3-0150....................!
2016-10-25 22:21:53 INFO     GTBinnedAnalysis.run_gtapp(): Generating SourceMap for galdiffCaught St13runtime_error at the top level: WcsMap2: Requested energy index is out-of-range.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/heatdeath/.local/lib/python2.7/site-packages/fermipy-0.10.0+9.g5cca-py2.7.egg/fermipy/gtanalysis.py", line 1006, in setup
    c.setup(overwrite=overwrite)
  File "/home/heatdeath/.local/lib/python2.7/site-packages/fermipy-0.10.0+9.g5cca-py2.7.egg/fermipy/gtanalysis.py", line 4603, in setup
    self._create_binned_analysis()
  File "/home/heatdeath/.local/lib/python2.7/site-packages/fermipy-0.10.0+9.g5cca-py2.7.egg/fermipy/gtanalysis.py", line 4659, in _create_binned_analysis
    self._obs = ba.BinnedObs(**utils.unicode_to_str(kw))
  File "/home/heatdeath/fermi_science/ScienceTools-v10r0p5-fssc-20150518A-source/x86_64-unknown-linux-gnu-libc2.19-0/lib/python/BinnedAnalysis.py", line 44, in __init__
    pyLike.AppHelpers_checkExposureMap(srcMaps, binnedExpMap)
  File "/home/heatdeath/fermi_science/ScienceTools-v10r0p5-fssc-20150518A-source/x86_64-unknown-linux-gnu-libc2.19-0/lib/python/pyLikelihood.py", line 4567, in AppHelpers_checkExposureMap
    return lib_pyLikelihood.AppHelpers_checkExposureMap(*args)
RuntimeError: File not found: /home/heatdeath/fermi_science/science/srcmap_00.fits

**Comment by woodmd** [comment]
It looks like it's crashing when trying to generate the source map for the galactic diffuse component.  What energy selection are you using?  I suspect that you are trying to use a selection that is wider than the energy range of the galactic diffuse model (roughly 50 MeV to 500 GeV).  The energy selection parameters (`select.emin` and `select.emax`) must fall within the energy range of all mapcube components in your model.
